### ISSUE TITLE
Additional attack icons

### ISSUE THREAD

**Issue by geordanr** [geordanr/xwing-miniatures-font#10]
We are missing the special attack icons for Firespray and YV-666.

@armoredgear7 @Hinny

**Comment by Kumagoro42** [comment]
Ghost has one, too.

**Comment by geordanr** [comment]
It actually doesn't:

![Hera Syndulla](http://vignette3.wikia.nocookie.net/xwing-miniatures/images/7/7a/Hera-ghost.png/revision/latest?cb=20151204222236)

Unlike the Firespray or the YV, it doesn't have an auxiliary arc -- it has a "special arc" which does not apply to primary weapons.

**Comment by Kumagoro42** [comment]
Right, you're correct. It only works if you set that up during squad building.

**Comment by armoredgear7** [comment]
geordanr - here are the fonts with the wave 8 ships and both aux firing arc icons.
https://www.dropbox.com/sh/m1g67tlfsyv4ozg/AADXkxOWL5xmqHDNkYFDIHe3a?dl=0

**Comment by geordanr** [comment]
There seems to be an issue with the icons for energy, SLAM, and Tallon rolls -- is that happening to anyone else or did I mess up font loading somehow?
