### ISSUE TITLE
Victory Counter icons

### ISSUE THREAD

**Issue by sirjorj** [geordanr/xwing-miniatures-font#100]
![victorycounters](https://user-images.githubusercontent.com/6219508/71036608-a5d3af00-20e3-11ea-9f82-e6a5160e926a.jpg)

**Comment by ScottKarch** [comment]
I'm not sure if the actual shape looks good or if a simplified version would work better.. Thoughts?
![image](https://user-images.githubusercontent.com/19825797/71333907-85e82500-2501-11ea-8eee-b2a76321b0fd.png)

**Comment by sirjorj** [comment]
Thank you much for these updates!

**Comment by sirjorj** [comment]
There maybe a use case for having a version of the victory point icon without the circle: 
![214906EB-5BD9-4DB6-822C-7B12F71336A9](https://user-images.githubusercontent.com/6219508/71375011-6ba25b80-2582-11ea-889a-e53aedbc6566.jpeg)

**Comment by ScottKarch** [comment]
Original I’m guessing. Not simplified.   Any thoughts on simplified vs original or keep both?  there are way more character slots available in the font but it will be hard for people to use them via keyboard.

**Comment by sirjorj** [comment]
I would vote for original but without the circle around it.

**Comment by ScottKarch** [comment]
sirjorj, I agree that for the single point icon to be used for documentation/rules, the original more detailed makes the most sense for me as well.  I'll get that done and I'll also work on the better strain icon with the knockout

**Comment by ScottKarch** [comment]
This was added to the last release. I think it can be closed.
