### ISSUE TITLE
new characters and changes to square token shapes

### ISSUE THREAD

**Issue by ScottKarch** [geordanr/xwing-miniatures-font#101]
I'd like to offer up the following changes.  I've changed all the square tokens to the shape I think looks more accurate to the cardboard, I've moved a couple glyphs that are not yet in production, and added the black versions of the new icons/tokens.

thoughts?
BEFORE
![image](https://user-images.githubusercontent.com/19825797/71602034-d07a2a80-2b1b-11ea-91de-3d280f48087e.png)

AFTER
![image](https://user-images.githubusercontent.com/19825797/71602041-d708a200-2b1b-11ea-93ec-57f832b46449.png)

I also removed the simplified points for now.  I can add them back if anyone needs them.

**Comment by sirjorj** [comment]
Looks great!  And I see a victory point without the circle.  Care to post this version so I can test it?

**Comment by ScottKarch** [comment]
I’m finishing some detailed and simple initiative markers and then I’ll post.

**Comment by sirjorj** [comment]
Sounds good - thanks!

**Comment by ScottKarch** [comment]
![image](https://user-images.githubusercontent.com/19825797/72109422-6b80ba80-32fb-11ea-8891-8147102dcc6f.png)
[xwing-miniatures 2020 jan 9.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/4042813/xwing-miniatures.2020.jan.9.ttf.zip)

**Comment by ScottKarch** [comment]
Font uploaded..  all changed from above in this font.  deplete, updated squares, and 4 versions of the initiative token black and white.

**Comment by geordanr** [comment]
Awesome, thanks!  I'll work on updating files this weekend.  Can you supply the list of codepoints that were changed?  It's hard to tell what some of the characters are from the screenshots.

**Comment by ScottKarch** [comment]
Yes.  I’ll get everything noted. Lots of additions and a few changes     I’ll note what’s new and what was modified.  Quite a few hours into this build.

**Comment by ScottKarch** [comment]
Name | Status | Glyph Name | Unicode Value | Unicode Character
Strain Token | Update | N | U+004e | N
Command | New | V | U+0056 | V
Stress Token Black | Update | Eacute | U+00c9 | É
Point Icon | New | Igrave | U+00cc | Ì
3 Point Token | New | Iacute | U+00cd | Í
1 Point Token | New | Icircumflex | U+00ce | Î
3 Point Token Black | New | Idieresis | U+00cf | Ï
1 Point Token Black | New | Eth | U+00d0 | Ð
Ion Token black | Update | adieresis | U+00e4 | ä
Cloak Token Black | Update | aring | U+00e5 | å
Ion Token | Update | oacute | U+00f3 | ó
Cloak Token | Update | ocircumflex | U+00f4 | ô
Strain Icon | Update | asciicircum | U+005e | ^
Strain Token |   | otilde | U+00f5 | õ
Strain Token Black |   | odieresis | U+00f6 | ö
Deplete Token | New | divide | U+00f7 | ÷
Deplete Token Black | New | oslash | U+00f8 | ø
First Player 1 | New | Lacute | U+0139 | Ĺ
First Player 1 Black | New | lacute | U+013a | ĺ
First Player 2 | new | uni013B | U+013b | Ļ
First Player 2 Black | New | uni013C | U+013c | ļ
First Player 3 | New | Lcaron | U+013d | Ľ
First Player 3 Black | New | lcaron | U+013e | ľ
First Player 4 | New | Ldot | U+013f | ľ
First Player 4 Black | New | ldot | U+0140 | ŀ

Yuck, bad formatting, but this has all the glyphs I added/updated... I think  Based on the images I posted I think I caught them all.
