### ISSUE TITLE
Jan 2020 new Ships

### ISSUE THREAD

**Issue by ScottKarch** [geordanr/xwing-miniatures-font#103]
How many new ships are there?  If someone could provide me with a high resolution scan of the fireball 
 and Von Reg silhouettes I'll get them added.   Are there any other new ships or icons/tokens?

**Comment by ScottKarch** [comment]
I'll make 4 hyperspace tokens... the 3 sided ones for playing Aces High and include them... They might be useful in the future

**Comment by dbxau** [comment]
Not a scan but found the FFG cdn file

![I_Fireball](https://user-images.githubusercontent.com/5035125/73039747-55eac380-3eab-11ea-9ee7-fc5f8f71fe8b.png)

https://sb-cdn.fantasyflightgames.com/ship_types/I_Fireball.png

**Comment by ScottKarch** [comment]
Thanks...  those are usually good quality images.. but man, that's terrible looking
![image](https://user-images.githubusercontent.com/19825797/73104886-204ed600-3ebd-11ea-8c06-2cb2c0bc4479.png)

**Comment by ScottKarch** [comment]
with the rough bitmaps, this is the initial drawing. I may tweak them later.  
![image](https://user-images.githubusercontent.com/19825797/73125549-a165a600-3f6d-11ea-99f4-5ec5f5754efc.png)

![image](https://user-images.githubusercontent.com/19825797/73125550-a6c2f080-3f6d-11ea-93f4-2dea8f3addc9.png)

![image](https://user-images.githubusercontent.com/19825797/73125559-b3474900-3f6d-11ea-8bc9-f26d1e1cbca4.png)

Fireball
U+007c
|

VonReg
U+007b
{

[x-wing-ships 2020 Jan 24.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/4112410/x-wing-ships.2020.Jan.24.ttf.zip)

**Comment by sirjorj** [comment]
![baron](https://user-images.githubusercontent.com/6219508/74204434-bf532c00-4c38-11ea-9ac5-db21eb8991be.jpg)
![fireball](https://user-images.githubusercontent.com/6219508/74204436-c0845900-4c38-11ea-9a3b-470a0616116f.jpg)

**Comment by sirjorj** [comment]
![deplete](https://user-images.githubusercontent.com/6219508/74204537-3ab4dd80-4c39-11ea-9c73-e218a121e000.jpg)

**Comment by an6re** [comment]
Tried to improve the vectors. Does it helps?

[Vonreg.pdf](https://github.com/geordanr/xwing-miniatures-font/files/4226127/Vonreg.pdf)
[Fireball.pdf](https://github.com/geordanr/xwing-miniatures-font/files/4226130/Fireball.pdf)

**Comment by thomric2** [comment]
Is this issue stalled out?

**Comment by sirjorj** [comment]
Any updates on this?

**Comment by joemasilotti** [comment]
@ScottKarch I really appreciate all the work you do!

Is there anything holding up merging in the new characters to master? I would love to use the new ships. Thanks!

**Comment by danrs** [comment]
Paging @ScottKarch, let us know how we can help move this forward

**Comment by Camburu** [comment]
Hi I'm trying to figure out how I can contribute these. I create outlines for all the new ships as they are announced. 
![image](https://user-images.githubusercontent.com/32975113/97911717-9a3fa580-1d00-11eb-91e7-227d9b4e2af6.png)
