### ISSUE TITLE
Salvaged Astromech Icon

### ISSUE THREAD

**Issue by finnsea** [geordanr/xwing-miniatures-font#106]
I might be blind, but I'm not seeing a character for the Salvaged Astromech icon. Not sure if this is in 2nd Edition or not, as I only have 1st Edition content, but is someone able to point me to it or add it to the font?

**Comment by geordanr** [comment]
It was decided in #47 to use a new font file for second edition, and leave any first edition icons behind.  You can still get the Salvaged Astromech icon at the [last 1.x version](https://github.com/geordanr/xwing-miniatures-font/tree/v1.0.29).
