### ISSUE TITLE
Wave 9

### ISSUE THREAD

**Issue by geordanr** [geordanr/xwing-miniatures-font#11]
Need icons for:

Ships:
- ARC-170
- TIE/sf
- Protectorate Starfighter
- Lancer-class Pursuit Craft

Actions:
- Rotate Arc

**Comment by FedoraMark** [comment]
If you're looking for completeness, would it be possible to also add the EPIC icon and the FIRST ORDER icon?

**Comment by armoredgear7** [comment]
I think the font already includes the Epic icon, but not the Resistance or FO icons.

I just got back from Gencon, but I'll do these shortly.

**Comment by FedoraMark** [comment]
Oh it is? The Epic icon isn't in the LIST OF SYMBOLS; I guess I missed it in the actual font file.

The font's a great resource by the way, thanks for it!

**Comment by armoredgear7** [comment]
Yep, the Epic icon is the right bracket (shift+0).

**Comment by FedoraMark** [comment]
")"    \0029 ?
Yeah, that's missing from the CSS file. Thanks for letting me know.
