### ISSUE TITLE
Issue with xwing-miniatures-ships metadata

### ISSUE THREAD

**Issue by urbknu** [geordanr/xwing-miniatures-font#113]
The latest version of the **xwing-miniatures-ships** meta data has 
* a prefix of "MyFont" to the fontname
* the family name is set to "My Font"
* Name for Humans has a prefix of "My Font"

This corrupts the font naming, as all programs wanting to use the font, will need to use "My Font" instead of the right name "x-wing-ships".

**Comment by geordanr** [comment]
@CrazyVulcan can you update the TTF to fix the metadata?

**Comment by CrazyVulcan** [comment]
Sure i will this after
