### ISSUE TITLE
New ships don't appear in font

### ISSUE THREAD

**Issue by joemasilotti** [geordanr/xwing-miniatures-font#118]
Ships from the release in December don't seem to be appearing correctly when using the font.

I've installed the font to my machine (uninstalled the old one first) and selected it for this text field in Sketch. Note that the other (old) ships appear as expected.

<img width="532" alt="image" src="https://user-images.githubusercontent.com/2092156/104128263-6e055e00-531b-11eb-9c9b-267aafb5f39f.png">

**Comment by joemasilotti** [comment]
Looks like the font in `dist/` hasn't been updated, but the version in `src/fonts/` has. Copying over one to the other doesn't create a diff, though, which is very odd.

**Comment by geordanr** [comment]
I just installed font in dist locally and the new ships are appearing correctly; maybe there was some font caching issue going on?

**Comment by joemasilotti** [comment]
Yeah, that could be it. Oh well, closing!
