### ISSUE TITLE
Missing tag for v1.0.15

### ISSUE THREAD

**Issue by guidokessels** [geordanr/xwing-miniatures-font#13]
I see v1.0.15 hasn't been tagged yet. Could you create a tag? 

Also, the `gh-pages` branch still seems to be at v1.0.14.

**Comment by geordanr** [comment]
@Hinny are the changes on 1.0.15 complete?  I see the TTF was updated (and is smaller than the previous file; is that expected?) but no Sass or Pug files were updated.  What's new in the TTF?

Should we wait for the updates in #12 to make it into 1.0.15?

**Comment by Hinny** [comment]
Yes, they should be complete. The changes are detailed in the previous commit (https://github.com/geordanr/xwing-miniatures-font/commit/1b7633d4160667684e2fe0d17f624416cc3fcf97). In the future I will do pull requests, since I don't know how to build this.

**Comment by Hinny** [comment]
Maybe it is just a matter of pushing the same changes to the gh_pages branch?

**Comment by geordanr** [comment]
Yeah.  `gh_pages` should be identical to `master`.

So no new glyphs were added to the TTF?  Just optimization?

**Comment by Hinny** [comment]
Ok, sorry about that! I am away from my computer this weekend unfortunately, so I cannot push anything now.

Yes, basically optimization + salvage astromech got a face-lift.

**Comment by geordanr** [comment]
Pushed tag [v1.0.15](https://github.com/geordanr/xwing-miniatures-font/tree/v1.0.15)
