### ISSUE TITLE
Taller symbols cut off at top

### ISSUE THREAD

**Issue by nahanahs** [geordanr/xwing-miniatures-font#15]
Some of the taller maneuver symbols have a little of their tops cut off
![x-wing-icons](https://cloud.githubusercontent.com/assets/24990081/21750814/12136758-d58a-11e6-8ed2-aea0bb277499.png)

**Comment by armoredgear7** [comment]
The current set of maneuver arrows were taken from the FFG Rulebook download, and designed to line up with body text of the same font size. 

Here's a screenshot from the font-editing software I used, showing where the ascenders, etc line up. These arrows were taken fron the FFG rulebook download, and designed to line up correctly with other body text at the same font size. While I haven't seen the issue you've posted with the font, it's probably the result of the software you're using - It doesn't happen when I use this font with InDesign for example.
![screen shot 2017-01-08 at 12 13 50 pm](https://cloud.githubusercontent.com/assets/9486041/21751853/0f103a4c-d59c-11e6-8f35-946ef7510a50.png)

**Comment by nahanahs** [comment]
Strange. I'm seeing it on two different computers in Word, Excel, Photoshop and in the Windows Font Viewer (just the boost icon in that case, as it's all it shows)

**Comment by FedoraMark** [comment]
I've noticed this on my iPhone app. Though I just make the font size smaller to accommodate it, but regardless it can show up in some programs.

**Comment by nahanahs** [comment]
This appears to be some weird issue with Windows 10 (at least). I'm closing the issue, as I don't believe it's the font itself causing it.
