### ISSUE TITLE
Upsilon Quadjumper and TIE scans

### ISSUE THREAD

**Issue by ScottKarch** [geordanr/xwing-miniatures-font#16]
Here are Scans of the ship shapes/icons for the Upsilon, Quadjumper and Captured TIE
![capturedtie](https://cloud.githubusercontent.com/assets/19825797/22606578/fa708974-ea19-11e6-9692-6eb8538fd7dd.png)
![quadjumper](https://cloud.githubusercontent.com/assets/19825797/22606577/fa6a93c0-ea19-11e6-9b81-0e1948903daf.png)
![upsilon](https://cloud.githubusercontent.com/assets/19825797/22606586/02cd154c-ea1a-11e6-9ae2-be04855328bf.png)

**Comment by armoredgear7** [comment]
These have been added - Thanks for the scans!
