### ISSUE TITLE
Reverse Maneuver Icons

### ISSUE THREAD

**Issue by ScottKarch** [geordanr/xwing-miniatures-font#17]
Here are high resolution scans of the reverse left, reverse straight and reverse right maneuvers from a quadjumper dial.  I hope you can use them.
![reverseleft](https://cloud.githubusercontent.com/assets/19825797/22607098/071b4dce-ea1c-11e6-9615-d41b00565690.png)
![reversestraight](https://cloud.githubusercontent.com/assets/19825797/22607097/07192346-ea1c-11e6-9095-0e99890577b3.png)
![reverseright](https://cloud.githubusercontent.com/assets/19825797/22607099/071f9f96-ea1c-11e6-899f-926a20bd6cd2.png)

Feel free to contact me at scott@karchfamily.com if there is a better way to submit these to you.

**Comment by armoredgear7** [comment]
These have been added - Thanks for the scans!
