### ISSUE TITLE
tieadvancedprototype & yt2400freighter

### ISSUE THREAD

**Issue by dbxau** [geordanr/xwing-miniatures-font#19]
Hi!

I've just noticed that the font is using "xwing-miniatures-ship-tieadvancedprototype" and "xwing-miniatures-ship-yt2400freighter"

Will/should these be changed to the standard canonical/xws names?

Cheers!

Dennis

**Comment by geordanr** [comment]
Fixed in 38ba1db08b800fa19cfa41a7b4c304911303c5c1
