### ISSUE TITLE
Ship icons

### ISSUE THREAD

**Issue by geordanr** [geordanr/xwing-miniatures-font#2]
It would be nice to have the ship silhouette icons.

**Comment by Hinny** [comment]
I will not have the time to do this until summer, unfortunately. Here is a link to png:s of all the large and small ship icons if anyone else want to give this a try before then:
https://drive.google.com/folderview?id=0B0dD5k8AOOx2RHRuNUdYY19vdUE&usp=sharing

**Comment by armoredgear7** [comment]
I have this done; will send to Geordan today.

On Saturday, January 24, 2015, Hinny <notifications@github.com> wrote:

> I will not have the time to do this until summer, unfortunately. Here is a
> link to png:s of all the large and small ship icons if anyone else want to
> give this a try before then:
>
> https://drive.google.com/folderview?id=0B0dD5k8AOOx2RHRuNUdYY19vdUE&usp=sharing
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geordanr/xwing-miniatures-font/issues/2#issuecomment-71309159>
> .
>


-- 
Josh Derksen

**Comment by geordanr** [comment]
Awesome!

**Comment by geordanr** [comment]
@armoredgear7 did you email the file to me?  If so I haven't received it yet.

**Comment by geordanr** [comment]
Added in 011fb34e9d565d5167dfee681f0be4c4c3b40604
