### ISSUE TITLE
Wave XI ship icons

### ISSUE THREAD

**Issue by geordanr** [geordanr/xwing-miniatures-font#20]
[Wave XI](https://drafts.fantasyflightgames.com/en/news/2017/3/15/independent-operations/) is announced; we'll need ship icons for
 - Auzituck Gunship
- TIE Aggressor
- Scurrg H-6 Bomber

**Comment by FedoraMark** [comment]
Also for the C-ROC:

- C-ROC Cruiser
- Container Token (normal and inverted)

**Comment by Hinny** [comment]
I don't think the available images (only "card fans") are good enough to use at the moment. I will get to work when we have revealed ship cards for each ship type.

**Comment by Markums** [comment]
Scratch the Container Token, looks like it's gonna be a gameplay-placed obstacle like the Debris token. The Jabba card does confirm an **Illicit token** though so we'll need that and an inverted version.

**Comment by sirjorj** [comment]
![illicittoken](https://user-images.githubusercontent.com/6219508/26861271-59bb07f2-4b08-11e7-871a-bdf00511c5b3.jpg)

Is this adequate?

**Comment by sirjorj** [comment]
You'll probably want these too...
![base](https://user-images.githubusercontent.com/6219508/26877229-dd23f5a4-4b4e-11e7-8b0f-f989f7dcc627.jpg)
![card](https://user-images.githubusercontent.com/6219508/26877234-e11c9f58-4b4e-11e7-8c42-ca0ea12bcdd8.jpg)

**Comment by sirjorj** [comment]
Are those images good enough or do you need them flatbed scanned so there is no perspective skewing?

**Comment by sirjorj** [comment]
If it isn't, here's a scan:

![scan](https://user-images.githubusercontent.com/6219508/26902899-980ab85c-4ba0-11e7-87c5-e4030f54fb47.jpg)

**Comment by Hinny** [comment]
I think all the necessary icons are available now, but I don't have time to fix them at the time being. Others are welcome to do so, otherwise I will try to get them done when I get time.

**Comment by ScottKarch** [comment]
Here are a few higher resolution scans of the ship shapes if they help.    I'd be happy to create the vector outlines, what app should I use?  email me at scott@karchfamily.com and I'll give it a go.
![aggressor](https://user-images.githubusercontent.com/19825797/28331257-fc9310f0-6bb5-11e7-8b69-a20d2f1b9867.png)
![auzituck](https://user-images.githubusercontent.com/19825797/28331255-fc914b30-6bb5-11e7-9a30-5d975dc2765a.png)
![croc](https://user-images.githubusercontent.com/19825797/28331254-fc909b0e-6bb5-11e7-9a49-cfb676e1eb77.png)
![scurrg](https://user-images.githubusercontent.com/19825797/28331256-fc921b0a-6bb5-11e7-945c-f98189b99b9e.png)

**Comment by ScottKarch** [comment]
I just took my first go using FontForge.  I put the CROC in C, the Auzituck in @  the Aggressor in the tilde ` and the H-6 Scurrg in H.   No clue if they will help or not.. feel free to delete or clean up the vector work.

[x-wing-ships-sk.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/1163438/x-wing-ships-sk.ttf.zip)

**Comment by FedoraMark** [comment]
Awesome job, this'll do great for me while waiting on the existing font. I can fix sizing per ship in the app I use them in. :D

**Comment by ScottKarch** [comment]
Yeah.  I think I made them too big.   My first time using FontForge.

**Comment by ScottKarch** [comment]
OK.. I found the TRANSFORM feature to scale the glyph.   Here is how they look and an uploaded copy.   
![example](https://user-images.githubusercontent.com/19825797/28474818-92b8c024-6e0f-11e7-8506-33ef31fec781.png)
[x-wing-ships-SK2.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/1166247/x-wing-ships-SK2.ttf.zip)

**Comment by dhsilva-cit** [comment]
Unfortunately there is still a problem with the four new icons. All older icons are rectangular (3x4), but the new ones are square. Could it be fixed?

![image](https://user-images.githubusercontent.com/24941921/28480444-1be4e0ae-6e37-11e7-9909-0be2a9b31a02.png)

**Comment by ScottKarch** [comment]
Spending more time with the app.. I see how you started the ships below the baseline.. I moved the ships down and to the left to hopefully be more consistent with all the other..   And, now that I look at it, the C-ROC at R doesn't make as much sense as having it at 5   The 5th huge ship.
Attached is a tweaked font.
[x-wing-ships-SK4.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/1167049/x-wing-ships-SK4.ttf.zip)

**Comment by FedoraMark** [comment]
So just to clarify: C-ROC is "5" ?

**Comment by ScottKarch** [comment]
Think so.  On the update I just uploaded.   Croc should be 5 and I resized and reset the baseline on them all.

**Comment by FedoraMark** [comment]
![img_3804](https://user-images.githubusercontent.com/20897443/28495756-34041b8c-6f27-11e7-918e-bc1f2ca66344.png)
Here's an example of your new glyphs with the originals. Works great!
