### ISSUE TITLE
Wave XI Images

### ISSUE THREAD

**Issue by sirjorj** [geordanr/xwing-miniatures-font#28]
I think I have all the new elements here.

![2017-07-12-0003](https://user-images.githubusercontent.com/6219508/28137851-54906efc-6714-11e7-8f9f-4ec247bd6f32.jpg)
![2017-07-12-0002](https://user-images.githubusercontent.com/6219508/28137852-5492a672-6714-11e7-89c8-8cf77fda85db.jpg)
![2017-07-12-0001](https://user-images.githubusercontent.com/6219508/28137850-548bdc5c-6714-11e7-840c-a604e1fc12ed.jpg)

Thanks!

**Comment by geordanr** [comment]
@armoredgear7 @Hinny
