### ISSUE TITLE
Expand this to include all required fonts

### ISSUE THREAD

**Issue by sirjorj** [geordanr/xwing-miniatures-font#29]
This may be exceeding the scope of this project, so feel free to shoot it down it you don't want to go in this direction.

In addition to these fonts that provide the symbols and icons, the X-Wing Miniatures game uses 2 additional commercial fonts: Bank Gothic Medium BT and Kimberley Bl.

(note: i am no lawyer and font licensing is complex, so what follows is my understanding of how this works)

Bank Gothic has an alternative called Squarish Sans regular (http://christtrekker.users.sourceforge.net/fnt/squarishsans.shtml) that is released under the SIL Open Font License, which I think means you could add it to this collection.

Kimberley Bl is free for desktop use (https://www.fontspring.com/fonts/typodermic/kimberley) but the application license (which allows you to distribute it embedded in your program but not with your source code) is $57.  Since we only need this one for the numbers (this is what the stat values on the cards use), would it be difficult to create an open source font that only implements the digits 0-9 in a 'similar' manner?

Heck, depending on the terms of the OFL, perhaps one could fork Squarish, replace the digits with ones similar to Kimberley, and rerelease it as an X-Wing font (properly crediting the original creator, of course).

Thoughts?

**Comment by armoredgear7** [comment]
X-wing also uses Eurostile Condensed for the body text on all documents and cards, and Revenger BB for book headings. If we're talking about completeness here, you'd need those and they are also paid (somewhat expensive) fonts.

I don't think this is worth it, from a licensing or cost perspective.

**Comment by sirjorj** [comment]
Ahh... I didn't realize there were additional fonts as well.  Thanks for the heads up!

This project is mainly to assist in all sorts of free/opensource projects, so I never expected it to license commercial fonts but to find freely distributable ones that are 'close enough'.  I would think that most projects would be satisfied with the title and stat fonts (the ones I listed in the OP).  One has a free alternative and the other only needs the digits, so it shouldn't take too much effort to make a 'close enough' version.  I put fontforge on my linux machine and might play around with it this evening to see firsthand how difficult it would be.

As for the fonts you mentioned, they are more for the documentation that comes with the game and less for the style and presentation that define the look of the game, so I don't think those would be as useful.

Of course, I am looking at this through the lens of what I want for my project, so there is some bias there! :)  Though I do think the title and stat fonts would be the most useful for most of the fan projects out there.

**Comment by geordanr** [comment]
I would prefer to limit this project's scope to X-Wing glyphs, i.e. the things you can't get by accessing already-available fonts (like Eurostile, BankGothic etc.).

**Comment by sirjorj** [comment]
Right on.  I've been thinking about it more and my idea of changing the Squarish font to have the kimberley digits will not work because there are titles with numbers in them.  I am interested in making a simple font that only implements the 0-9 digits and maybe a few punctuation marks if necessary.  I will explore this idea this evening and if something comes of it, i will put it in a repo under my account.

Thanks!

**Comment by sirjorj** [comment]
If anyone is interested, I have actually made some progress on this:
https://github.com/sirjorj/xhud/tree/fontwork/fonts

This folder has Squarish Sans CT, which is the OFL alternative to Bank Gothic.

It also has xwstats, which is something I threw together.  It only has glyphs for the 10 digits and parentheses, but that is all I need.  I am releasing it under the OFL license as well (indicated in LICENSE in my project root directory).  If you want a free alternative to the commercial fonts, have at it!
