### ISSUE TITLE
Illicit Tokens

### ISSUE THREAD

**Issue by FedoraMark** [geordanr/xwing-miniatures-font#30]
Lost in the last update and issue closings was the newest game token:

- Illicit Token
- INVERTED Illicit Token

**Comment by FedoraMark** [comment]
![26902899-980ab85c-4ba0-11e7-87c5-e4030f54fb47](https://user-images.githubusercontent.com/20897443/28488349-8c794542-6e75-11e7-8d72-f1494954f426.jpg)

Sample image of illicit tokens from a previous issue thread

**Comment by ScottKarch** [comment]
I'll take a swing at it

**Comment by ScottKarch** [comment]
![illiciticons](https://user-images.githubusercontent.com/19825797/28494152-eb2056fa-6eeb-11e7-8bc6-0dc20761a7f2.png)
How does the Illicit token look.  There is so much detail, I can't imagine getting all the circles and lines in it.

**Comment by geordanr** [comment]
The Illicit token is inverted in the font.

Don't worry about the circles and lines; it's the [Aurebesh Credit symbol](http://starwars.wikia.com/wiki/Credit) that needs to be clear.

**Comment by ScottKarch** [comment]
LOL. Shows how much I run scum.  I'll flip and upload. Feel free to use, edit or discard

**Comment by ScottKarch** [comment]
I tried to add more detail and the icon got really messy... how do these look?
![illiciticons](https://user-images.githubusercontent.com/19825797/28533311-3827ad96-7062-11e7-87e6-31b4f0264472.png)
[xwing-miniatures-SK1.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/1170446/xwing-miniatures-SK1.ttf.zip)

**Comment by dhdasilva** [comment]
If you would suggest something, I'd say that you should invert the black/white of the border (make the corners/diagonal white and the straight black):

![illicit](https://user-images.githubusercontent.com/780428/28534269-8b0ae3f2-7076-11e7-9009-cf5e59eaf5ad.png)

But I think this change is'n needed and it is great the way it is!

**Comment by geordanr** [comment]
For clarity you could omit the border effects (similar to how it's done for the Extra Munitions token).  That way at smaller sizes the border doesn't start to interfere with the actual symbol.

**Comment by ScottKarch** [comment]
?
![credits](https://user-images.githubusercontent.com/19825797/28547287-d574a3f2-7093-11e7-819b-9c8d23e65525.png)

**Comment by geordanr** [comment]
Are these in the updated ZIP in #18 ?

**Comment by ScottKarch** [comment]
No..   I didn't see the request about the Credit token until after I uploaded the last go around..
attached is the font with the updated credits AND the solid and hollow astroids with the no changed numbers/locations..    Just the updated Credit
[xwing-miniatures-SKL4.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/1171462/xwing-miniatures-SKL4.ttf.zip)
