### ISSUE TITLE
Tallon Roll with bank template symbols

### ISSUE THREAD

**Issue by FedoraMark** [geordanr/xwing-miniatures-font#31]
So one of the new pilots for the StarVipers, Dalan Oberos, allows for Tallon Rolls using either the turn template (normal) or the bank template. So I think we should have a custom maneuver for it like what was added for IG-88D's ability.

This one should probably be the Signor's Loop but with the arrow mirrored (facing out instead of in).

I'm trying to set up Font Forge to help out with this but, alas, it doesn't appear to want to open on my machine
![swx73-dalan-oberos](https://user-images.githubusercontent.com/20897443/28547239-f9b58576-709b-11e7-959c-8629aea2f5d5.png)
 :(

**Comment by FedoraMark** [comment]
Managed to get another font program working, and while I learn how to export properly and can merge it with the Illicit Tokens additions in #30, here's what they look like compared to the original Tallon Rolls. (I'm gonna call these Signor's Rolls, and the IG-88D glyph can be Tallon Loop)

<img width="225" alt="t-loop" src="https://user-images.githubusercontent.com/20897443/28547848-d6c68828-709e-11e7-955a-cf562522671b.png">
<img width="331" alt="t-rolls" src="https://user-images.githubusercontent.com/20897443/28547849-d6c9e9e6-709e-11e7-8de1-2b0110f40b92.png">

**Comment by FedoraMark** [comment]
also noticed that the inverted condition symbol is misaligned (i think due to width). I'll fix that too

**Comment by shinayser** [comment]
You should not create icons that are not official. This might confuse
players. I do not recommend.

Em seg, 24 de jul de 2017 20:56, FedoraMark <notifications@github.com>
escreveu:

**Comment by FedoraMark** [comment]
True, but we did add a special arrow for IG-88D’s S-Loop with Turn template. And the Primary Weapon icons were split up for customization purposes.

Perhaps a third small font could be made to include the not-official glyphs?

**Comment by geordanr** [comment]
As @FedoraMark mentioned, there already are several unofficial icons in the font which are there for the convenience of users.  I don't expect that anyone considers this font authoritative in any way, so I don't see it as a real issue.

**Comment by FedoraMark** [comment]
Okay So here is what I've done. Using @ScottKarch 's version that includes the Obstacles and Illicit Tokens I've added 3 new glyphs: the T-Roll with Bank left and right (in "[" and "]") and added an inverted unique dot (in "•", bullet) (which i needed for something specific).
<img width="202" alt="s-rolls" src="https://user-images.githubusercontent.com/20897443/28635664-658ec4a6-7209-11e7-95fc-6cad7faf62f4.png">
<img width="109" alt="unique ring" src="https://user-images.githubusercontent.com/20897443/28635665-65904be6-7209-11e7-8654-cfeca7f5f18d.png">

I also fixed alignment for the inverted condition token
<img width="635" alt="fixed condition invert" src="https://user-images.githubusercontent.com/20897443/28635675-70f928a4-7209-11e7-9d84-7a5aea904b9f.png">

**Comment by FedoraMark** [comment]
I'm using a program other than FontForge and i'm not familiar with any issues that can arise with meta data for font files (glyphs all look fine though). But someone might want to merge/check/adjust things with these fonts:

[x-wing-symbols-fm2.zip](https://github.com/geordanr/xwing-miniatures-font/files/1177602/x-wing-symbols-fm2.zip)

**Comment by FedoraMark** [comment]
Closed with #35
