### ISSUE TITLE
Ship Outlines?

### ISSUE THREAD

**Issue by ScottKarch** [geordanr/xwing-miniatures-font#32]
I'm making some reference cards and outlined ships vs solid ships would make them visible but less distracting.   It's a lot of additional glyphs, but FontForge makes it very simple to do.  I can provide a few options of width you can select which you like and we can document the outline width to keep them consistent.   Thoughts?
![outline2](https://user-images.githubusercontent.com/19825797/28632992-e7a12cf2-71f7-11e7-9ff9-b731e63c4ac0.png)

Looks like some fonts have some issues and cleanup might be needed.. but that should probably be done anyway.

**Comment by ScottKarch** [comment]
Is this something you'd like me to do and would want in the font?

**Comment by geordanr** [comment]
I'm neutral on this; anyone else on the project have opinions either way?

**Comment by FedoraMark** [comment]
Neutral as well.

**Comment by ScottKarch** [comment]
Ok.  I'll hold off for now. It's a lot of work.  Thanks.
