### ISSUE TITLE
Wave XII + XIII icons

### ISSUE THREAD

**Issue by FedoraMark** [geordanr/xwing-miniatures-font#35]
Icons that will be needed for Wave XII (known as of Aug 26):

Ships:
- Alpha-class Attack Wing
- Sheathipede-class Shuttle (Phantom II)
- M12-L Kimogila Fighter

Icons:
- Reload Action
- Bullseye Arc
- Bullseye Arc separated
- Jam Token
- Jam Token inverted

and if possible add in the 3 icons and 1 change from #31

**Comment by FedoraMark** [comment]
Also Wave XII:

Ships:
- Resistance Bomber
- TIE Silencer

**Comment by sirjorj** [comment]
My preorder is scheduled to be delivered today.  I will make some high-res scans and post them here as soon as I can.

**Comment by sirjorj** [comment]
Here are the new things - let me know if I missed any.

![bsf17](https://user-images.githubusercontent.com/6219508/33683555-ebc845fc-da90-11e7-9312-5d2c9b4581fa.jpg)
![bullseye](https://user-images.githubusercontent.com/6219508/33683556-ebdf2812-da90-11e7-92b7-14519f6b1307.jpg)
![gunboat](https://user-images.githubusercontent.com/6219508/33683557-ebf7c098-da90-11e7-9360-c5a98cd3e497.jpg)
![jam](https://user-images.githubusercontent.com/6219508/33683559-ec107d86-da90-11e7-83c8-47c71afbe0b2.jpg)
![kimo](https://user-images.githubusercontent.com/6219508/33683560-ec288b4c-da90-11e7-9351-487a229650ab.jpg)
![rattled](https://user-images.githubusercontent.com/6219508/33683562-ec44109c-da90-11e7-9dca-81062c1bf44a.jpg)
![reload](https://user-images.githubusercontent.com/6219508/33683563-ec5d4fda-da90-11e7-93d1-9554a18c7e6b.jpg)
![sheath](https://user-images.githubusercontent.com/6219508/33683564-ec7909be-da90-11e7-8579-aa328be041c4.jpg)
![silencer](https://user-images.githubusercontent.com/6219508/33683565-ec8eed06-da90-11e7-8664-cc0a8ea8e9d0.jpg)

**Comment by corsairjoe** [comment]
![bsf-17](https://user-images.githubusercontent.com/34491102/33908169-53390f78-df3c-11e7-8db4-f644e9bb13a5.png)

Let me know if this is ok. I can try to do some other ones, too.

**Comment by geordanr** [comment]
Looks good!

**Comment by sirjorj** [comment]
Excellent!

**Comment by ScottKarch** [comment]
good scans.   I still can't figure out what I'm missing in the glyphs I've
created.  They work for some things and not others.  I am planning on
fixing them, but I'm not sure what's wrong with them.  What apps do you
guys use?

**Comment by FedoraMark** [comment]
I maintain this iPhone app: https://itunes.apple.com/us/app/ship-cards-for-x-wing/id1139594637?mt=8

**Comment by sirjorj** [comment]
I maintain xhud (https://github.com/sirjorj/xhud) and its underlying library (https://github.com/sirjorj/libxwing)

**Comment by kalhamaar** [comment]
I maintain xwing-font-converter (https://github.com/kalhamaar/xwing-font-converter) a utility tool used to convert all font element to images

**Comment by piffopi** [comment]
Hi Guys
are you still working on this font?

I just managed to download fontforge, and was wondering if you are already implementing wave 12 and 13 (would be silly to do the same work twice)

**Comment by piffopi** [comment]
Here are the PNG scans of the missing ships. let me know how you want to proceed, and if these need to be transformed in a vector file. please specify the format, so i can provide the proper one on monday if needed :)

![tie aggressor](https://user-images.githubusercontent.com/30245582/34640310-9444d656-f2f0-11e7-8042-3fe73d787cb4.png)
![gunboat](https://user-images.githubusercontent.com/30245582/34640311-94634884-f2f0-11e7-857b-c4cfdeb729d2.png)
![kimogila](https://user-images.githubusercontent.com/30245582/34640312-9481cd18-f2f0-11e7-96d2-fc7f07a80f55.png)
![phantom2](https://user-images.githubusercontent.com/30245582/34640313-949ea76c-f2f0-11e7-800c-f6163a730657.png)
![silencer](https://user-images.githubusercontent.com/30245582/34640314-94bbe296-f2f0-11e7-9fc4-c8716c677284.png)
![scurrg](https://user-images.githubusercontent.com/30245582/34640315-94dc9234-f2f0-11e7-8037-f81e4ed7357b.png)
![auzituck](https://user-images.githubusercontent.com/30245582/34640316-94fa4522-f2f0-11e7-9e3d-94e6d4fa7814.png)

**Comment by sirjorj** [comment]
That gunboat looks great!  The rest look a little... lumpy. :)  Can you smooth out the lines any?  It would improve their look and probably decrease their size as well.
Thanks for doing this!

**Comment by piffopi** [comment]
Sure thing! I'll do it asap. The gunboat was done manually, the others
automatically. Give me half an hour and you'll have them

Il 6 gen 2018 4:36 PM, "sirjorj" <notifications@github.com> ha scritto:

**Comment by sirjorj** [comment]
Wow, that was fast!  Thanks!  I figured they were auto-conversions.  High res scans of low-res images can only do so much.

**Comment by piffopi** [comment]
Yeah, also I don't have illustrator on my notebook - so I had to rely on
photoshop.

Il 6 gen 2018 4:41 PM, "sirjorj" <notifications@github.com> ha scritto:

**Comment by piffopi** [comment]
First three are here. Now i'm going back to aggressor, auzituck and the scurrg. just let me find decent scans

![kimogila](https://user-images.githubusercontent.com/30245582/34641459-0149bb40-f305-11e7-81b1-eb9c7cc4c428.png)
![silencer](https://user-images.githubusercontent.com/30245582/34641460-0198ec06-f305-11e7-9f37-2fdb76cd05f2.png)
![phantom2](https://user-images.githubusercontent.com/30245582/34641461-01b68a18-f305-11e7-9d63-76253da08791.png)

**Comment by piffopi** [comment]
W11 v2
the scans in the other thread allowed me to re-do this :)
hope it helps. now, on to the other glyphs.

![tie aggressor](https://user-images.githubusercontent.com/30245582/34641710-9ca37114-f308-11e7-8c58-6544926fae95.png)
![scurrg](https://user-images.githubusercontent.com/30245582/34641711-9cc2b632-f308-11e7-8a24-bc38b9eadb0d.png)
![auzituck](https://user-images.githubusercontent.com/30245582/34641712-9ce101dc-f308-11e7-8a7c-4c14fc9a8a42.png)

**Comment by piffopi** [comment]
bullseye!

![bullseye](https://user-images.githubusercontent.com/30245582/34641781-85845150-f309-11e7-882c-86e3a83d3d6e.png)

**Comment by piffopi** [comment]
reload

![reload](https://user-images.githubusercontent.com/30245582/34641919-4de05d6e-f30b-11e7-9c02-e099f2211fc2.png)

**Comment by piffopi** [comment]
jam action

we should be ok now :) 
lemme know if you guys can integrate them in the fonts, or i'll try to do it

![Uploading jam.png…]()

**Comment by piffopi** [comment]
sorry, forgot the frog 🗡 
![phantom2](https://user-images.githubusercontent.com/30245582/34642122-7c8f2fa2-f30e-11e7-84a4-9bcf297c9147.png)

**Comment by FedoraMark** [comment]
Looking great!

**Comment by Owen-A** [comment]
Is anything else needed now we have the scans above? Happy to help fi it gets things moving.

**Comment by piffopi** [comment]
We need to compile and update the font.

My experience with fontforge is really limited, so is taking me an awful amount of time to scale properly the images.

in alternative, i can do it with another software but i'll have to recompile the whole font.

**Comment by Owen-A** [comment]
I am not an expert, just an enthusiastic user of the font, but if you want the images at a specific scale let me know the dimensions and format and i will try and assist

**Comment by piffopi** [comment]
thank you :)
i'm proficient in Photoshop and Illustrator so there's no problem regarding that. My main issue is understanding what is the target dimension for this images. Does anybody know?

**Comment by FedoraMark** [comment]
[xwing-glyphs-update.zip](https://github.com/geordanr/xwing-miniatures-font/files/1628127/xwing-glyphs-update.zip)

I'm using BirdFontNonCommercial and not FontForge, and I don't really know vector tools outside of Flash/Animate, but here's a quick and dirty update to the symbol fonts to include Reload Action (=), Bullseye (?), and Bullseye top separated (’ (right quote, &rsquo;)). The reload action is a computer trace from the above png with some tweaks and the bullseye is hand-traced from the png and positioned to match the existing Front-Back turret.

It's a bit sloppy but if you don't need to blow up the glyphs it should work. It's using the font I had my other changes in from #31 

Jam token and invert variant ignored for now since we have the JAM action icon and blank token/inverts.

**Comment by FedoraMark** [comment]
Updated zipped font file to fix sizing of the bullseye symbol (see previous comment for updated files).

**Comment by piffopi** [comment]
Thanks so much guys :)

Il 14 gen 2018 3:23 AM, "FedoraMark" <notifications@github.com> ha scritto:

**Comment by geordanr** [comment]
What are the actual codepoints of the new symbols?

**Comment by FedoraMark** [comment]
reload icon is EQUALS SIGN: https://www.fileformat.info/info/unicode/char/003d/index.htm
full bullseye is QUESTION MARK: http://www.fileformat.info/info/unicode/char/3f/index.htm
separated bullseye is RIGHT SINGLE QUOTATION MARK: https://www.fileformat.info/info/unicode/char/2019/index.htm

and from #31 
left 'tallon loop' is LEFT SQUARE BRACKET: http://www.fileformat.info/info/unicode/char/005b/index.htm
right 'tallon loop' is RIGHT SQUARE BRACKET: http://www.fileformat.info/info/unicode/char/005d/index.htm
outline bullet is BULLET: http://www.fileformat.info/info/unicode/char/2022/index.htm

I'll try to do the ships in the next day or two, plus the change in #39

**Comment by geordanr** [comment]
Included in tag v1.0.27.

I named them "tallon loops" (tloop) in the CSS (based on your original post) but I can rename it.  What's the source of that?  Is that just for Dalan Oberos?

**Comment by FedoraMark** [comment]
Thanks, couldn’t remember how I named them compared to the unique Tallon Roll arrows we added for IG-88D.

And yes, currently just Dalan Oberos (and by extension Thweek mimicking Dalan).

**Comment by FedoraMark** [comment]
Oops, looks like I forgot to fix the Bullseye separated’s size when I edited the font. I’ll fix that up and re-post the font when I do the ships.

**Comment by FedoraMark** [comment]
Here's the updated Ships based on the glyphs above (and fixed the Y-position of the Auzituck, #39):
[xwing-ships-update.zip](https://github.com/geordanr/xwing-miniatures-font/files/1630144/xwing-ships-update.zip)

Also updated the symbols font to fix the Bullseye Separated/Overlay:
[xwing-glyphs-update.zip](https://github.com/geordanr/xwing-miniatures-font/files/1630143/xwing-glyphs-update.zip)

Hopefully this works for everyone!

**Comment by geordanr** [comment]
Incorporated into v1.0.28.

I renamed the maneuver one to `dalan-bank{left,right}` to match the convention of `ig88d` maneuvers already in the font.

**Comment by sirjorj** [comment]
First, thanks to everyone who helped with this!

Second, a couple questions:
1) What all was done to the actual ttf files?  one of them doubled in size since the previous version and the other tripled.
2) Re: dalan-bank - is there a symbol for this that is used in any actual FFG product or publication, or is this just a custom symbol based on the description that is on the card?

Thanks again everyone.  And I am an at-least-one-of-everything for this game so when future releases come out, I can make and post high-res scans of any relevant parts again if it would be helpful.

**Comment by FedoraMark** [comment]
1. Could be the program that I'm using. It's a free one called BirdFontNonCommercial and not FontForge. I don't know much about font files and optimization, so if anyone can re-export the files as smaller please do.

2. The Dalan Bank is just a custom one based on the description; we did something similar for IG-88D's custom maneuver as well. See #31 for some info.

**Comment by sirjorj** [comment]
Ahh.  Right on.  Thanks for clarifying.

**Comment by haslo** [comment]
Just wanted to say "thank you" to all involved. You guys are awesome!
