### ISSUE TITLE
Missing icons from the iconlist

### ISSUE THREAD

**Issue by delicatesther** [geordanr/xwing-miniatures-font#36]
Hi guys,

I've been working on a soundboard for X-wing and I've been trying to add the Auzituck gunship. I see that it is included in the icon list, however adding the class icon brings the character space up blank. Trying to add it myself as a :before element in the X-wing font family also doesn't seem to work. 
And finally (probably most obviously); when checking out the font I don't see the icon listed in the font repertoire. Is it possible some are missing?

**Comment by guidokessels** [comment]
Strange, it works for me. Is it only the Auzituck that doesn't work for you?

**Comment by delicatesther** [comment]
OK I am thoroughly baffled. I created a test file using all icons in the
icon list, they display just fine. For some reason the icon does not work
in my regular markup, though (I copy pasted, so it's not a spelling
problem). I'll keep testing and see whether I can find the problem.

**Comment by delicatesther** [comment]
No there is quite a few missing, I made a list.  See enclosed screenshot (every list item should have the corresponding icon preceding it, but as you can see there are quite a few blank spaces). 
![image](https://user-images.githubusercontent.com/15010802/30521276-60835ade-9bbd-11e7-86f6-99903e438496.png)

**Comment by ScottKarch** [comment]
It looks like they are the things I've worked on.   If someone can tell me what I'm doing wrong, I'll fix them and start making characters correctly.  I just use them as a font only.  Sorry for whatever it is I am doing wrong.

**Comment by Conzar** [comment]
Same for me.  I have tried loading the font in both gimp and inkscape and I am also missing the c-roc, auzituck, etc.

**Comment by ScottKarch** [comment]
I apologize. I do t know what I did wrong.  The glyphs seem to work for most apps but not everything. 

I'm guessing it's something I did and not something wrong with the app.  I'll try and edit the glyphs from another app.   If anyone can tell me what I did wrong I'll fix the glyphs.   


Scott Karch
