### ISSUE TITLE
Reload Action Icon

### ISSUE THREAD

**Issue by voidstate** [geordanr/xwing-miniatures-font#37]
Hi guys

The Star Wing has a new action: reload.

![image](https://user-images.githubusercontent.com/1204122/32192497-3d250090-bdac-11e7-97a3-ab35f24d7813.png)

![image](https://user-images.githubusercontent.com/1204122/32192528-54ee3d68-bdac-11e7-92dd-1ec9d2b62160.png)

Is anyone working on this?

**Comment by geordanr** [comment]
Fixed in #35
