### ISSUE TITLE
Missing icon for energy

### ISSUE THREAD

**Issue by geordanr** [geordanr/xwing-miniatures-font#4]
I know, I'm never satisfied~

**Comment by armoredgear7** [comment]
Oh, haha, yeah. 

I think there might also a special primary attack icon for the Firespray with front/back arrows or something if you want to get really specific.

**Comment by geordanr** [comment]
Yeah, that one's not super necessary.  But I want to move away from using the png sprite, and at this point I think it's only the energy icon that's not in the font.
