### ISSUE TITLE
Higher Quality Auzituck

### ISSUE THREAD

**Issue by FedoraMark** [geordanr/xwing-miniatures-font#41]
The Auzituck glyph is pretty low quality. Can anyone make a sharper vector or PNG trace (black on white) of the glyph and I can add it to the font file?
<img width="367" alt="sloppyauzituck" src="https://user-images.githubusercontent.com/20897443/35127807-9b64b272-fc81-11e7-91f7-e468ae0cd9e6.png">

**Comment by ScottKarch** [comment]
Here is  scan off a token..   the original outline is kind of funky to
begin with.

[image: Inline image 1]

**Comment by FedoraMark** [comment]
I don’t think your image posted

**Comment by ScottKarch** [comment]
Here is the scan off a base token I used.  It's pretty funky to beginwith.  There are a couple corners that could use tightening up.

**Comment by ScottKarch** [comment]
![auzituck2](https://user-images.githubusercontent.com/19825797/35419770-868cd1e4-01ff-11e8-8d1c-0f464996a6cf.png)
Here is the scan I used to trace the ship.   A coupld of the corners can be tighter. The silhouete is kind of funky to begin with.
![auzituck](https://user-images.githubusercontent.com/19825797/35419813-bf85e3d2-01ff-11e8-9cce-47bbfcc06f4f.png)

**Comment by FedoraMark** [comment]
Thanks. And yeah doesn't look like we'll get much refinement. I'll give it a go next time we need to add other new ships.

**Comment by emeraldbeacon** [comment]
![image](https://user-images.githubusercontent.com/38739187/41196005-9fa2998c-6bec-11e8-97af-99e68d91d9b4.png)

I did a vector version of this... would it work for your purposes?

**Comment by FedoraMark** [comment]
Looks much better than the current one, we should probably add this when the TIE Reaper is added

**Comment by ScottKarch** [comment]
I just traced the image off of the online squad builder and came up with this.
![image](https://user-images.githubusercontent.com/19825797/45768354-4944c400-bc02-11e8-8a71-e9944d3a2211.png)

**Comment by ScottKarch** [comment]
The online app should give us easy access to reasonable quality art from FFG

**Comment by ScottKarch** [comment]
[x-wing-ships-Auz-SK.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/2398003/x-wing-ships-Auz-SK.ttf.zip)
