### ISSUE TITLE
Fore/Aft reinforce token

### ISSUE THREAD

**Issue by vitreuz** [geordanr/xwing-miniatures-font#46]
I noticed there's only the standard reinforce token, but the directional reinforce token from the Auzituk expansion isn't listed. I'm wondering if there are plans to add it?

**Comment by ScottKarch** [comment]
this is in the action bar....   once I start going down this road I'm sure I'll make all the dotted circles.   How do these look?

![image](https://user-images.githubusercontent.com/19825797/40984028-8b9d439a-68a6-11e8-82d4-d1117fdb6ead.png)

![image](https://user-images.githubusercontent.com/19825797/40984041-92e446a8-68a6-11e8-87f8-f66b8fd66a0c.png)

![image](https://user-images.githubusercontent.com/19825797/40984047-95f75614-68a6-11e8-9df6-361b1ade7098.png)

**Comment by ScottKarch** [comment]
I'm guessing the reinforce action icon is only the front one...   we probably won't need the rear one..  But until we see the tokens Ill hold on to the graphic
