### ISSUE TITLE
2nd Edition

### ISSUE THREAD

**Issue by sirjorj** [geordanr/xwing-miniatures-font#47]
Might as well start on this:

- Should it be a whole separate project or build on this one?
- What icons need to be added?

**Comment by urbknu** [comment]
1. might be an idea to make a project? I am figuring the backwards compatibility will be pretty painful. 
2. I have noticed the following changes; Force, colored coordinate, some kind of charge (this will be painful to keep track of in the hud)

**Comment by geordanr** [comment]
I think we could incorporate new stuff into this project.  It looks like many of the icons (like upgrades and actions) are staying the same, so we shouldn't need to duplicate them.

In terms of colored actions, that's outside the scope of fonts, which don't care about colors anyway.  Presently, things like attack/agility/shield/hull are colored by applications.

**Comment by urbknu** [comment]
I agree, @geordanr

**Comment by mludowise** [comment]
It’s probably difficult to say at this point, but does anyone have a sense for if any of the ship icons are getting updated?

**Comment by sirjorj** [comment]
I went through the released images.  Here are the new elements I saw (and some that may not be new but might be a little different or more detiled).

![180arc_text](https://user-images.githubusercontent.com/6219508/39968418-45fcf0cc-5692-11e8-9470-d2f315195ed9.png)
![evade_focus_charge_tokens](https://user-images.githubusercontent.com/6219508/39968425-467a8bf4-5692-11e8-86ed-8e801894002f.png)
![force_stat](https://user-images.githubusercontent.com/6219508/39968426-468d12e2-5692-11e8-91d4-d77b96157d99.png)
![force_text](https://user-images.githubusercontent.com/6219508/39968427-469c1f12-5692-11e8-8999-52f319bb68d9.png)
![frontarc_stat](https://user-images.githubusercontent.com/6219508/39968428-46b90f1e-5692-11e8-9225-173208ac0ae5.png)
![frontarc_text](https://user-images.githubusercontent.com/6219508/39968429-46c8b054-5692-11e8-9b02-060cd956efd2.png)
![gunner_maybe](https://user-images.githubusercontent.com/6219508/39968430-46d9c826-5692-11e8-8b7b-0b7c4a0393b1.png)
![gunner_text](https://user-images.githubusercontent.com/6219508/39968431-46ea7ee6-5692-11e8-9314-b687015bbc53.png)
![linked_actions](https://user-images.githubusercontent.com/6219508/39968432-46f8b2c2-5692-11e8-999b-dfebb8b52b88.png)
![lock_stat](https://user-images.githubusercontent.com/6219508/39968433-4708b9ec-5692-11e8-9773-1e905296e3cc.png)
![lock_text](https://user-images.githubusercontent.com/6219508/39968434-471aa6f2-5692-11e8-8723-b14829943f02.png)
![mod_or_title](https://user-images.githubusercontent.com/6219508/39968435-4728f8ce-5692-11e8-9ed6-8fd2144b3ccd.png)
![reararc_stat](https://user-images.githubusercontent.com/6219508/39968436-47386f16-5692-11e8-95a0-8400f236e37b.png)
![reararc_text](https://user-images.githubusercontent.com/6219508/39968437-4746c0e8-5692-11e8-92b3-2c6da3337cd3.png)
![reinforce_stat](https://user-images.githubusercontent.com/6219508/39968438-47564eaa-5692-11e8-9d80-594d6076e537.png)
![shield_lock_tokens](https://user-images.githubusercontent.com/6219508/39968439-4765a256-5692-11e8-8126-a0e452e896cb.png)
![torpedo_stats](https://user-images.githubusercontent.com/6219508/39968440-47771be4-5692-11e8-8249-8bbd2faab8c3.png)
![turretarc_text](https://user-images.githubusercontent.com/6219508/39968441-47887f24-5692-11e8-9aa1-d80676ce9677.png)

















![bullseyearc_text](https://user-images.githubusercontent.com/6219508/39968419-460e06e6-5692-11e8-8f0e-11a9898c7c7b.png)
![calc_cloak_force_tokens](https://user-images.githubusercontent.com/6219508/39968420-461e4916-5692-11e8-9625-c33830ba4bfc.png)
![calculate_text](https://user-images.githubusercontent.com/6219508/39968421-4630258c-5692-11e8-8ae7-5a7f88b1c050.png)
![charge_stat](https://user-images.githubusercontent.com/6219508/39968422-464001f0-5692-11e8-8b49-6c615f6584f2.png)
![charge_text](https://user-images.githubusercontent.com/6219508/39968423-465177aa-5692-11e8-8f01-df2191614626.png)
![elite](https://user-images.githubusercontent.com/6219508/39968424-466a5658-5692-11e8-89a2-432042f5dc3e.png)

**Comment by ScottKarch** [comment]
I'd vote to keep it in the same project.

**Comment by Hinny** [comment]
I also agree that we keep it in the same project, however, I think a new font-file for 2nd edition is warranted so that it will not get too large and confusing with all the new arcs and token shapes and stuff. The ship silhouettes seems to be identical so lets just continue with that.

**Comment by geordanr** [comment]
Do we know if any icons are _changing_ from 1.0 to 2.0?  Because if not, then most 2.0 users will have to source from two TTFs -- one for icons that haven't changed (focus, evade, etc.), and one for the icons that are new in 2.0 (arcs, etc.).  That seems unnecessarily cumbersome to me.  There's plenty of unused codepoints in the font files, and the new icons don't really need to have human-readable codepoints like we were trying to have in the past.

**Comment by Hinny** [comment]
I was thinking we duplicate the ones that is used in both versions so that one contains all you need for 1st edition and one contains all you need for 2nd edition. Then you will use the ship font for both 1st and 2nd. For me it feels better not to mix the two versions in the same font.

**Comment by mludowise** [comment]
Duplicating the same icons in two font files seems error prone to me. I vote to just replace any existing icons that will change (and I don’t know if there actually are any) and add new icons to the same file. If the concern is that someone wants to use the old icon set or doesn’t need any new icons, then they should use the last 1.x released version. I’m also assuming we’ll likely start versioning 2.x when 2nd edition is integrated.

**Comment by geordanr** [comment]
Good point -- the version will get bumped to 2.0 once we get the new icons in.

**Comment by ScottKarch** [comment]
I’ve started a custom font for 2.0 glyphs I need for the custom damage deck I’m giving to groups/podcasts.    Right now it’s a single glyph.    I’ll post it if it will help.   Maybe someone can tell me what is missing from the glyphs I’ve made.  Why some people can’t use them but most can.

**Comment by ScottKarch** [comment]
[Force.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/2049807/Force.ttf.zip)
1 character font    F for force

**Comment by ScottKarch** [comment]
![image](https://user-images.githubusercontent.com/19825797/40806857-5a273da0-64e8-11e8-8801-f7925b74aa39.png)

**Comment by ScottKarch** [comment]
[XWing2E.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/2059980/XWing2E.ttf.zip)

**Comment by Owen-A** [comment]
@ScottKarch You need the bullseye one as well.

**Comment by ScottKarch** [comment]
Sure. I’ve been making them as I need them or see them.  I’ll look for it and fix the arcs. 


Scott Karch

**Comment by ScottKarch** [comment]
[XWing2Ev2.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/2063259/XWing2Ev2.ttf.zip)

**Comment by ScottKarch** [comment]
if any of you can test which apps or ways of using my glyphs fails, would you please try and figure out what I'm missing and why the glyphs work for most apps but not all?

**Comment by ScottKarch** [comment]
I'm wondering if we want to have multiple glyphs..  many items can be seen on tokens with circle/broken circle/dotted circle outlines.    I think that it's worth having both available.

**Comment by sirjorj** [comment]
First, thank you so much for getting started on this!  They look great!

For the new firing arc icons, are all the circles the same?  As in, if you would overlay all of the different firing arc icons, would the outer circles perfectly overlap each other?  I think when I was working with the upgrade icons a while back, I got the impression that all the outer circles were not quite the same - though it could have been just an artifact of the size I was rendering them.  Also don't forget the 180 (front half) arc and the double turret.  For the double turret, you may want to rescale the single turret so the inner circle is centered.  I think the double turret is just the single turret with the extra point.

Regarding the weird dot/dash circles around the stat icons... I'm pretty sure it is just eye candy.  Personally, I have no use for it, but I'm sure there are some who would find it handy.  I think the real question is how to scale it.  Should there be "Shield Icon" and "Shield-with-weird-dotted-outline-thing Icon"?  If separate, should they both have the shield icon be the same size but one has the outline thing extending around it?  Or should the outlined one be smaller?

So how soon can these be integrated into the main icon font? :)

**Comment by ScottKarch** [comment]
180 degree arc too.  


Scott Karch

**Comment by ScottKarch** [comment]
![image](https://user-images.githubusercontent.com/19825797/40859136-56ec53e6-65a6-11e8-99cd-56674c3d88f7.png)
I've been trying very hard to make all the circles the same size.  Exporting and Importing SVG does not keep the same size... grr.  I've been copy/pasting overlapping glyphs and resizing by % to try and get them the same size.  It's about as close as I can get.

**Comment by ScottKarch** [comment]
the mobile arc and mobile 180 degree arc have the same sized up/right triangle and circles line up.  The 180 just has more glyph to the lower left.

**Comment by ScottKarch** [comment]
[XWing2Ev3.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/2063873/XWing2Ev3.ttf.zip)
I'd rather someone else look them over before putting them in the font... and where they go isn't a decision I'd like to make.     I really would like someone to test them too.

**Comment by ScottKarch** [comment]
![image](https://user-images.githubusercontent.com/19825797/40862319-c0a70488-65b1-11e8-9979-37197001bfe7.png)

**Comment by ScottKarch** [comment]
[XWing2Ev4.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/2064056/XWing2Ev4.ttf.zip)

My attempt at gunner.   The images available are pretty low resolution.  I'm sure it will be easier to make a better one with a high res scan

**Comment by ScottKarch** [comment]
![image](https://user-images.githubusercontent.com/19825797/40863135-69d9c520-65b4-11e8-89ec-63eb1d8a0ea0.png)
I think I'm done for the day

**Comment by ScottKarch** [comment]
[XWing2Ev5.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/2064102/XWing2Ev5.ttf.zip)
that's the new modification, right?  Looks like  a turbofan?

**Comment by sirjorj** [comment]
Wow.  That looks great!  And that is the new “Config” upgrade type.

**Comment by ScottKarch** [comment]
![image](https://user-images.githubusercontent.com/19825797/40866720-f2fb3770-65c4-11e8-944e-8f6fd391caa0.png)

Gunner Y
Energy g
force h
upgrade n
mobile arc p
mobile 180 arc q
front arc {
rear arc |
bullseye }
180 arc ~

**Comment by ScottKarch** [comment]
[xwing-miniatures-SK7.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/2064392/xwing-miniatures-SK7.ttf.zip)
Someone please look this over

**Comment by sirjorj** [comment]
Did some testing today - looks great!
The 'g' icon is called Charge (Energy is already in play for epic games).
The 'n' icon is called Config.
I think I've heard the devs throw around Turret Arc and Double Turret Arc but I'm not sure how solid those terms are.

I am hoping to get a new version of xwing.cgi (http://xhud.sirjorj.com/xwing.cgi) pushed out later today so then you could see for yourself how good it looks!

**Comment by ScottKarch** [comment]
Great..   I'll keep my eye out for it.  Feel free to move glyphs around etc.   Just trying to get the stuff knocked out.   Thanks for the update.   The gunner will definitly get an update once I get a high res scan.  But it's a start.    I'm confident all the circles are the same size an nearly identically in the same place.

**Comment by sirjorj** [comment]
Found another one - the Calculate icon (that weird mechanical eyeball-looking thing that the droid pilots have).

**Comment by sirjorj** [comment]
Do we need one for that little triangle arrow used in linked actions?  If so, the tricky part will be getting the position of it right.

**Comment by geordanr** [comment]
Speaking of little triangles, we should probably have one for the recharge icon (the little upward facing triangle).

**Comment by sirjorj** [comment]
Good call!
I just pushed an update to xwing.cgi (http://xhud.sirjorj.com/xwing.cgi) - it is now using the SK7 version of the font.  (you may need to nuke your browser cache to force it to pull the new font file)

**Comment by ScottKarch** [comment]
![image](https://user-images.githubusercontent.com/19825797/40882318-edc9f072-66a3-11e8-9bec-23005e2f786f.png)

**Comment by sirjorj** [comment]
Very nice!

**Comment by ScottKarch** [comment]
[xwing-miniatures_SK8.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/2065549/xwing-miniatures_SK8.ttf.zip)

Do we know what font is used for the charge numbers to get an idea of size of the little charge triangle?

**Comment by ScottKarch** [comment]
looking at scans.. the charge lightning bolt is pointed, not flattened at the ends...

**Comment by ScottKarch** [comment]
[xwing-miniatures_SK9.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/2065555/xwing-miniatures_SK9.ttf.zip)
Look at the charge glyph.  It has points now but had to slide up slightly  to have the bottom of the lightning bolt stay at the same decending line

**Comment by ScottKarch** [comment]
![image](https://user-images.githubusercontent.com/19825797/40882387-e8bdbf94-66a5-11e8-94f0-440f64d92809.png)

**Comment by sirjorj** [comment]
heh... i was just about to push the last version!  i will go with 9 instead.

**Comment by sirjorj** [comment]
Examples:
http://xhud.sirjorj.com/xwing.cgi/ship2?ship=aggressor
http://xhud.sirjorj.com/xwing.cgi/pilot2?pilot=idenversio&faction=imperial&ship=tiefighter

I am using them at a very small size but they still look good.

**Comment by ScottKarch** [comment]
nice.. thanks

**Comment by geordanr** [comment]
The font used for numerical stats is [Kimberley](https://www.dafont.com/kimberley.font).

**Comment by sirjorj** [comment]
When I looked into the fonts a while back, I think I remember Kimberley not being a free font.  To avoid possible licensing issues, I made a similar one but only made glyphs for the numbers and a few punctuation symbols (https://github.com/sirjorj/xhud/blob/master/fonts/xwstats.ttf).

**Comment by Hinny** [comment]
Great job @ScottKarch ! Thanks for doing this!

@sirjorj : I think the repo you linked to is private. I cant see it anyway...

**Comment by sirjorj** [comment]
Download the latest release (linux or macos) at xhud.sirjorj.com, extract it, and look in the fonts folder.

**Comment by geordanr** [comment]
Updated the project and bumped to 2.0.0.

**Comment by emeraldbeacon** [comment]
Some minor things you may want to include:
A linked action arrow
A very small "recharge" arrow

Notable is that the Salvaged Astromech slot is apparently no longer in use - now, Astromechs are all under the same icon, and are separated by faction when applicable.

**Comment by ScottKarch** [comment]
...  should we have 4 standard arc.. one for each 90 degrees?  For using when you can not rotate the character?   I wouldnt be surprised if my arcs are not quite right.    The images I used were not that clear.. I could be off by a bit.

**Comment by sirjorj** [comment]
That is probably the right call.  Also, for the 'full front' and 'full rear' arcs, is looks like the shaded half is exaggerated a bit - just like the quarters are actually a bit more than a quarter.

I'll scan the front arc on one of my cards.

**Comment by sirjorj** [comment]
FrontArc, Lock, Charge. some other new things...
![2018-06-29-0003](https://user-images.githubusercontent.com/6219508/42115488-ab9d2708-7bb8-11e8-9b6d-732c96a00655.jpg)

**Comment by sirjorj** [comment]
I think that's all the new stuff in Wave 14

**Comment by emeraldbeacon** [comment]
that "range" icon is new, isn't it?  The one on Proton Torpedoes, next to "2-3", that looks like a slice of pie?  Also, where did that missile image go, that was on previous iterations of that card?
![image](https://user-images.githubusercontent.com/38739187/42115850-96aa34bc-7ba9-11e8-83ad-11f1509e0797.png)

**Comment by sirjorj** [comment]
There are a few subtle differences between the previewed second edition card images and the cards that released in Wave 14.  The range icon, Faction restriction (images have text "REBEL", "IMPERIAL", etc - W14 cards have faction icon).

I'm guessing the W14 cards were at the printer when some more refinement was done.
