### ISSUE TITLE
TIE Reaper icon

### ISSUE THREAD

**Issue by FedoraMark** [geordanr/xwing-miniatures-font#48]
I know everyone's all giddy over the 2.0 icons but I think we're still missing the TIE Reaper silhouette.

**Comment by ScottKarch** [comment]
if someone posts a high res scan I'll give it a shot.  Nothing I've seen has enough detail

**Comment by sirjorj** [comment]
Were there any other new things in the wave that I should scan?

**Comment by sirjorj** [comment]
![reapericon](https://user-images.githubusercontent.com/6219508/41943154-fa992e04-7967-11e8-8742-48df6ea9c14c.jpg)

**Comment by sirjorj** [comment]
![krennic](https://user-images.githubusercontent.com/6219508/41943233-46771e6c-7968-11e8-9279-147ac43dbda6.jpg)
I don't remember if you make glyphs for condition tokens, but if you do, here's Krennic.

**Comment by ScottKarch** [comment]
![image](https://user-images.githubusercontent.com/19825797/42064396-ade986cc-7afb-11e8-9e25-50fad41a2ee4.png)
Scan vs 1st attempt.  The middle "hole" is tricky

**Comment by ScottKarch** [comment]
sure.. cardboard is always rougher..    upgrade and pilot cards have a real smooth finish and better detail... especially at the magnification needed.  I don't like the cutout/hole shape but recreated it 3-4 times and never liked it.   If you scan the pilot card I'll try again

**Comment by ScottKarch** [comment]
as for condition tokens..   since they are photos/images I just dont know how to standardize other than a hexigon with the condition name in it.

**Comment by ScottKarch** [comment]
a little 3D clip on harpoon to clip on the ship would be hilarious for the harpooned condition.  LOL

**Comment by sirjorj** [comment]
![2018-06-29-0001](https://user-images.githubusercontent.com/6219508/42106418-a2b9a36a-7b99-11e8-83b0-8dac481b4d3f.jpg)

**Comment by sirjorj** [comment]
For harpooned, a little model of a missile cut in half with rare earth magnets and some felt (so as not to scratch the model) could be fun!

Hope this scan helps.

**Comment by sirjorj** [comment]
For a 3rd opinion, here's a medium base:
![2018-06-29-0002](https://user-images.githubusercontent.com/6219508/42106690-8b8131c6-7b9a-11e8-93ac-2510c9c4b1f3.jpg)

**Comment by ScottKarch** [comment]
![image](https://user-images.githubusercontent.com/19825797/42114631-52fc64ea-7bb5-11e8-8b0f-3ae62f224c7c.png)

**Comment by ScottKarch** [comment]
![image](https://user-images.githubusercontent.com/19825797/42114769-e4140848-7bb5-11e8-807a-8870d9d38560.png)

**Comment by ScottKarch** [comment]
![image](https://user-images.githubusercontent.com/19825797/42114778-ebab5502-7bb5-11e8-970a-d92ef472eeee.png)

**Comment by ScottKarch** [comment]
... zoomed in on the detail areas

**Comment by sirjorj** [comment]
Cool.  Glad that worked better.

**Comment by ScottKarch** [comment]
[x-wing-ships-SK-Reaper1.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/2150978/x-wing-ships-SK-Reaper1.ttf.zip)
![image](https://user-images.githubusercontent.com/19825797/42115689-8b4997d8-7bb9-11e8-9e92-d0e30ac505b5.png)
![image](https://user-images.githubusercontent.com/19825797/42115694-9547a324-7bb9-11e8-9acd-f2b636cafa3d.png)
Let me know what you think

**Comment by oSPANNERo** [comment]
Would love to see this get merged.

**Comment by ScottKarch** [comment]
The font is zipped up and posted above.  Don’t know how to submit or if I can.    I think there is also something else people do


If someone wants to write up a how to doc I will help all I can.

**Comment by ScottKarch** [comment]
HAS Anyone downloaded the font and tested it?

**Comment by sirjorj** [comment]
Can confirm it works: http://xhud.sirjorj.com/xwing.cgi/ship2?ship=tiereaper

**Comment by geordanr** [comment]
Updated to v2.0.2.
