### ISSUE TITLE
Ordnance-type Icon

### ISSUE THREAD

**Issue by emeraldbeacon** [geordanr/xwing-miniatures-font#49]
![image](https://user-images.githubusercontent.com/38739187/41195702-866b896a-6be7-11e8-8c12-5bdbe9b3552f.png)

See that little missile icon next to the range limitations of the attack?  That represents an "Ordnance" type of secondary weapon, which ignores range combat bonuses (as opposed to Cannons and Turrets, which now are affected by range).

Just another icon to consider in the grand scheme of things...

**Comment by ScottKarch** [comment]
I'll need a much higher res scan to get an accurate glyph made   I think we need to wait for official cards to come out to add this as well as fix any incorrect details in the 2.0 glyphs made

**Comment by emeraldbeacon** [comment]
It happens to look a lot like the missile in the "reload" icon.  No evidence that it *IS* the same shape, but hopefully there will be some  crossover there.
