### ISSUE TITLE
SLAM action icon

### ISSUE THREAD

**Issue by geordanr** [geordanr/xwing-miniatures-font#5]
Can we get a trace of the new SLAM action icon added to the font?

![SLAM Reference Card](https://images-cdn.fantasyflightgames.com/filer_public/7b/3a/7b3a36da-2744-41e9-a490-4866da8cb3b8/swx33_card_ref_04.png)

**Comment by armoredgear7** [comment]
Already done. Will send you the updated font tomorrow

On Monday, April 20, 2015, Geordan Rosario <notifications@github.com> wrote:

> Can we get a trace of the new SLAM action icon added to the font?
>
> [image: SLAM Reference Card]
> <https://camo.githubusercontent.com/d114a26afa259b820afd1affe1c6d7405c3b0458/68747470733a2f2f696d616765732d63646e2e66616e74617379666c6967687467616d65732e636f6d2f66696c65725f7075626c69632f37622f33612f37623361333664612d323734342d343165392d613439302d3438363664613863623362382f73777833335f636172645f7265665f30342e706e67>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geordanr/xwing-miniatures-font/issues/5>.
>


-- 
Josh Derksen

**Comment by armoredgear7** [comment]
Check your messages on QA.
