### ISSUE TITLE
A few small things...

### ISSUE THREAD

**Issue by sirjorj** [geordanr/xwing-miniatures-font#51]
* `targetlock` should be `lock`
* It seems weird that the icons map is \u#### codes but the ships map is "#" characters.  Going to all \u codes would be more consistent
* Obstacle glyphs are probably obsolete unless 2nd edition is reusing the same shapes.
* Why are the token-cloak and token-evade glyphs gone?

**Comment by Hinny** [comment]
* Agreed on the lock issue.
* Consistency is always good
* We know at least some of the asteroid and debris shapes are identical to old ones. I would not be surprised if they all reappear eventually. We also don't know if the shapes not included in core box are tournament legal or not. I suggest waiting with removing them until we know more. 
* I removed all the tokens that had shapes no longer corresponding with the actual tokens. If evade token is gone, it was a mistake made by me.
