### ISSUE TITLE
anyone have high res scans of the scum falcon and escape craft?

### ISSUE THREAD

**Issue by ScottKarch** [geordanr/xwing-miniatures-font#57]
I'd like to get the scum falcon and escape craft glyphs made but I need a high res scan off either a pilot card or ship base.

**Comment by emeraldbeacon** [comment]
It's hardly hi-res, but... does this help?
![image](https://user-images.githubusercontent.com/38739187/44820289-0bc1bd80-aba5-11e8-9e15-ab4ffea9489f.png)

**Comment by ScottKarch** [comment]
thanks.. but that's not enough detail..  could you try and scan/crop the ships as large as possible?   This is what the falcon looks like blown up..   
![image](https://user-images.githubusercontent.com/19825797/45257529-1c282400-b36d-11e8-9f3b-529a34f70325.png)

**Comment by ScottKarch** [comment]
Hmmm   I tried to rotate a 3D model to get the same outline as the silhouette.  Then trace it with vectors..   I'm not crazy about it..    mostly because I don't have a good feeling of what it looks like close up   
![image](https://user-images.githubusercontent.com/19825797/45257803-a1add300-b371-11e8-842a-a019e0b13d0f.png)

**Comment by ScottKarch** [comment]
![image](https://user-images.githubusercontent.com/19825797/45257920-96f43d80-b373-11e8-8e13-1fd88eebe8cd.png)
[x-wing-ships-sk.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/2363651/x-wing-ships-sk.ttf.zip)

**Comment by ScottKarch** [comment]
someone sent me a higher res scan of both.  Please reveiw
![image](https://user-images.githubusercontent.com/19825797/45258570-77631200-b37f-11e8-8be0-8db197b43d3e.png)
[x-wing-ships-sk2.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/2363722/x-wing-ships-sk2.ttf.zip)
