### ISSUE TITLE
Faction Icons for Republic, Separatist

### ISSUE THREAD

**Issue by emeraldbeacon** [geordanr/xwing-miniatures-font#59]
A recent X-Wing article talking about the 2nd Edition Release Party seems to have revealed the icons for the Republic and Separatist factions.  More information here:  https://www.fantasyflightgames.com/en/op/x-wing/second-edition-launch-party/

![image](https://user-images.githubusercontent.com/38739187/45249754-922f7b00-b2da-11e8-843d-a3025053c893.png)

**Comment by ScottKarch** [comment]
![image](https://user-images.githubusercontent.com/19825797/45257455-44fbe980-b36c-11e8-971a-247c4d111362.png)

**Comment by ScottKarch** [comment]
Someone take a look at those two icons/symbols please
[xwing-miniatures-sk.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/2363612/xwing-miniatures-sk.ttf.zip)

**Comment by geordanr** [comment]
Looks good; let's merge this change into a single file with #57.

**Comment by geordanr** [comment]
Oh wait, that's a ships file, never mind~
