### ISSUE TITLE
What do you think of these glyphs for Base sizes?

### ISSUE THREAD

**Issue by ScottKarch** [geordanr/xwing-miniatures-font#60]
I've seen something similar on a few sites and thought I'd try and make a B/W version for a font.  Most of them are 2 color.. making this work as single color took a little work.   Any thoughts on me adding these 4 glyphs..   All, Small, Medium and Large   
![image](https://user-images.githubusercontent.com/19825797/45258978-489d6980-b388-11e8-9732-060c79440efa.png)

**Comment by ScottKarch** [comment]
![image](https://user-images.githubusercontent.com/19825797/45259087-36242f80-b38a-11e8-8c37-26fc636d5ef6.png)

**Comment by ScottKarch** [comment]
If you like them, it's the last update ( 2 new factions ) plus base sizes.
[xwing-miniatures-Bases-SK.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/2363795/xwing-miniatures-Bases-SK.ttf.zip)

**Comment by Hinny** [comment]
Looks good! Go for it!

**Comment by ScottKarch** [comment]
I just downloaded the current shipping and added them
![image](https://user-images.githubusercontent.com/19825797/45769144-58c50c80-bc04-11e8-81b9-4b5fdd54805d.png)

**Comment by ScottKarch** [comment]
[xwing-miniatures-bases-SK.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/2398021/xwing-miniatures-bases-SK.ttf.zip)
