### ISSUE TITLE
Customized YT-1300 and Escape Craft missing

### ISSUE THREAD

**Issue by FreakyDug** [geordanr/xwing-miniatures-font#62]
I downloaded the latest dist file for the ships font and found that the Customised YT-1300 (W) and Escape Craft (X) had disappeared:
![image](https://user-images.githubusercontent.com/2656101/45929295-83d29780-bf47-11e8-93e0-92f300da440b.png)

**Comment by ScottKarch** [comment]
had to be me..  I must have not been editing the current shipping file when I uploaded the fixed Auzituck.  Sorry.  I just copied the fixed Auz into the previous falcon/escape font.
[x-wing-ships-auz-falcon.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/2412187/x-wing-ships-auz-falcon.ttf.zip)
