### ISSUE TITLE
Scavenged YT-1300 icon

### ISSUE THREAD

**Issue by sirjorj** [geordanr/xwing-miniatures-font#63]
The Resistance Millennium Falcon is now called the "Scavenged YT-1300" and has a different icon.

https://images-cdn.fantasyflightgames.com/filer_public/f9/27/f9276fd7-52fd-4b05-8599-05039fa479e6/swz19_a2_reys-pilot.png

**Comment by ScottKarch** [comment]
this can probaly be closed... merged with the Wave 2 icons

**Comment by geordanr** [comment]
Covered in #69
