### ISSUE TITLE
Wave 3

### ISSUE THREAD

**Issue by sirjorj** [geordanr/xwing-miniatures-font#65]
I'm not sure if any of these are usable, but here is what I got so far...
![factions](https://user-images.githubusercontent.com/6219508/48296154-e54bb880-e458-11e8-9bdc-2016f99c8dae.png)
![republic](https://user-images.githubusercontent.com/6219508/48296155-e54bb880-e458-11e8-9785-63921d1a3463.png)
![separatist](https://user-images.githubusercontent.com/6219508/48296156-e54bb880-e458-11e8-9791-0b93489c07c0.png)
![sithinfiltratpr](https://user-images.githubusercontent.com/6219508/48296157-e54bb880-e458-11e8-9f07-e2c4c1e14fcc.png)
![tacticalrelay](https://user-images.githubusercontent.com/6219508/48296158-e5e44f00-e458-11e8-8c7d-ad9421af9400.png)

**Comment by sirjorj** [comment]
The official squad builder has the Wave 3 stuff live!

**Comment by an6re** [comment]
Here are the JPGs
![I_Belbullab-22](https://user-images.githubusercontent.com/48838057/54844322-8b90b000-4cce-11e9-9596-390dae78f369.jpg)
![I_Delta-7](https://user-images.githubusercontent.com/48838057/54844323-8b90b000-4cce-11e9-88bf-a78022b79431.jpg)
![I_SithInfiltrator](https://user-images.githubusercontent.com/48838057/54844325-8c294680-4cce-11e9-8ff0-9c79652d5eaf.jpg)
![I_V-19Torrent](https://user-images.githubusercontent.com/48838057/54844326-8c294680-4cce-11e9-8e79-c5a253a8ac4e.jpg)
![I_VultureDroid](https://user-images.githubusercontent.com/48838057/54844328-8c294680-4cce-11e9-8b24-900698f48ee2.jpg)
