### ISSUE TITLE
Tactical Relay

### ISSUE THREAD

**Issue by sirjorj** [geordanr/xwing-miniatures-font#71]
Is this big enough for someone to make the glyph or are we going to wait until release?

![swz29_kraken](https://user-images.githubusercontent.com/6219508/51428979-6947bc80-1bcf-11e9-9a4f-a9c5dfbd0fd7.png)

**Comment by ScottKarch** [comment]
should be fine... I'll try in the next day or two

**Comment by ScottKarch** [comment]
![image](https://user-images.githubusercontent.com/19825797/52452779-0a100480-2b0a-11e9-8159-4680f934b9e4.png)
?

**Comment by ScottKarch** [comment]
how does that look?

**Comment by sirjorj** [comment]
like Crow from MST3K :)

Nice work!

**Comment by ScottKarch** [comment]
![image](https://user-images.githubusercontent.com/19825797/52498099-62dcad00-2b9d-11e9-8fd3-0663dcb3d201.png)

**Comment by ScottKarch** [comment]
![image](https://user-images.githubusercontent.com/19825797/52503776-151b7100-2bac-11e9-8230-43ba99f30cc7.png)
Hmm   not crazy about it...   advice?

**Comment by FreakyDug** [comment]
It looks good to me. I think the original icon is weird and it's not clear what it's supposed to be, but you've reproduced FFG's work faithfully.

**Comment by sirjorj** [comment]
Yeah, it looks fine.  I think it is based off of a droid from the clone wars animated series.

**Comment by sirjorj** [comment]
Any chance of this getting pushed out soon?  I'd love to add it to xwing.cgi.

**Comment by ScottKarch** [comment]
[xwing-miniatures TacRelay.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/2873400/xwing-miniatures.TacRelay.ttf.zip)
Tactical Relay is Z   capital Z    If someone wants to teach me how to do the rest of the work to commit a font and the other entries needed for it, I'd be happy to learn.   Otherwise I'm happy just working on glyphs.

**Comment by ScottKarch** [comment]
here is is next to other characters    
![image](https://user-images.githubusercontent.com/19825797/52918940-818c2380-32c2-11e9-833b-2386472d5fcf.png)

**Comment by geordanr** [comment]
The easiest way to update the TTF in the project is to upload the file into the `src/fonts` folder; you can do it directly by going to https://github.com/geordanr/xwing-miniatures-font/upload/master/src/fonts (make sure you use the correct filename, either `xwing-miniatures-ships.ttf` or `xwing-miniatures.ttf`).

In the form at the bottom, add a short description of the update (for example, "Adds Tactical Relay glyph."), and an optional longer description in the larger text area if you'd like.  Select "Create a **new branch** for this commit and start a pull request") and then click "Commit changes" and voila, you've submitted a pull request with new TTFs!  Once that's done and I review it, I'll update the rest of the files to incorporate the new glyph.

**Comment by ScottKarch** [comment]
Thank you. I’ll try it next release.

**Comment by sirjorj** [comment]
what you have looks good - http://xhud.sirjorj.com/xwing.cgi/upgrades2

**Comment by ScottKarch** [comment]
Thanks. :)


Scott Karch

**Comment by raithos** [comment]
@geordanr Would love to get this live so I can include it into YASB <3

**Comment by elistevens** [comment]
https://github.com/geordanr/xwing-miniatures-font/pull/74 is up.
