### ISSUE TITLE
Change CSS Selector for MG-100 StarFortress sf-17

### ISSUE THREAD

**Issue by iwerts** [geordanr/xwing-miniatures-font#75]
The CSS selector for the MG-100 StarFortress sf-17 is currently
`i.xwing-miniatures-ship-mg100starfortress:before {
  content: "Z"; }`

If possible, update this selector to the following for consistency
`i.xwing-miniatures-ship-mg100starfortresssf17:before {
  content: "Z"; }`

**Comment by geordanr** [comment]
We use the XWS canonicalized name for the ship, which is based on the name of the ship on the card.  This agrees with what's in xwing-data2 (see the change at https://github.com/guidokessels/xwing-data2/commit/057472e8f2bf60335b3426b6bea944d95543430f#diff-cb0b13bbe766bd6266167531d062b188).
