### ISSUE TITLE
Galactic Republic and Separatist Alliance

### ISSUE THREAD

**Issue by ScottKarch** [geordanr/xwing-miniatures-font#76]
![image](https://user-images.githubusercontent.com/19825797/55049041-8908c000-5018-11e9-8c56-b411ebcbd841.png)
Here is a swing at it.  
Delta-7 [/backslash]  \
SithInfiltrator [/bracketright]  ]
Torrent [/asciicircum]  ^
Vulture [/underscore]  _
Belbullab [/bracketleft] [

**Comment by ScottKarch** [comment]
[xwing-miniatures-ships-SK.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/3011395/xwing-miniatures-ships-SK.ttf.zip)
If someone can test and let me know that would be great.  I got the file to Gold Squadron for streaming this weekend.

**Comment by an6re** [comment]
The all look great! I've found some differences in the Sith Infiltrator:
![Sith](https://user-images.githubusercontent.com/48838057/55069110-39a7ab80-507b-11e9-9438-b8c259becfae.jpg)
Mainly that empty space in the right wing. Also the bottom left wing is more linear and the wing joint is less prominent.

Vulture:
![Vulture](https://user-images.githubusercontent.com/48838057/55069121-42987d00-507b-11e9-97c2-95c521e5004f.jpg)
This is a really small thing, but the grapplings on the right seem a bit closer and harder to set apart when the font is used in small sizes.

**Comment by ScottKarch** [comment]
Thanks.  Not sure how the knockout got lost.  I’ll look at the other areas too. 


Scott Karch

**Comment by ScottKarch** [comment]
The knockout was there, but the direction needed to be reversed..
And I tweaked both ships.   Attaching the SVGs if someone wants to massage them.

[SVGs.zip](https://github.com/geordanr/xwing-miniatures-font/files/3014018/SVGs.zip)

[xwing-miniatures-ships-SK2.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/3014014/xwing-miniatures-ships-SK2.ttf.zip)

**Comment by ScottKarch** [comment]
![image](https://user-images.githubusercontent.com/19825797/55091214-6b6e4180-507e-11e9-9150-34f821033c05.png)

**Comment by an6re** [comment]
Seems perfect!

**Comment by ScottKarch** [comment]
Thanks.. not perfect, but good enough is good enough.   It's so difficult when you get in there real tight on a greyscale bitmap with a soft edge, to know where to place the vector line.
![image](https://user-images.githubusercontent.com/19825797/55099337-83998d00-508d-11e9-9641-9c42397e8763.png)

**Comment by ScottKarch** [comment]
@geordanr   I'd be happy to try the upload. It looks like my account may need different access.  
![image](https://user-images.githubusercontent.com/19825797/55099670-205c2a80-508e-11e9-8c4f-ffe14826c65e.png)

**Comment by elistevens** [comment]
@ScottKarch you're going to have to fork the repo, make your commit on your fork, and then submit the PR for @geordanr to merge. 

His work is... Particular about open source contributions, so if he did the commits himself, copyrights get gnarly.

**Comment by ScottKarch** [comment]
@geordanr I just forked the code and think I followed your directions.   Let me know how it looks.
https://github.com/ScottKarch/xwing-miniatures-font/compare/master...ScottKarch-Wave-2?expand=1
