### ISSUE TITLE
Gas clouds

### ISSUE THREAD

**Issue by techillin** [geordanr/xwing-miniatures-font#78]
Any progress on the new gas cloud obstacles?

https://raithos.github.io/images/gascloud1.png
https://raithos.github.io/images/gascloud2.png
https://raithos.github.io/images/gascloud3.png

**Comment by ScottKarch** [comment]
![image](https://user-images.githubusercontent.com/19825797/67224541-09e53a00-f3f7-11e9-9dc7-858b43a720ab.png)

**Comment by ScottKarch** [comment]
[/Emacron] triangleish outline Ē
[/Iogonek] triangleish solid Į
[/emacron] claw outline ē
[/iogonek] claw solid į
[/Ebreve] bacon outline Ĕ
[/Idotaccent] bacon solid İ
[/comma] Fuse ,

Text to test
, ,  F F  _ _  Ē  Ē  ē ē  Ĕ Ĕ  Į Į  į į  İ İ
![image](https://user-images.githubusercontent.com/19825797/67227650-43b93f00-f3fd-11e9-9993-0e5097bc6895.png)

[xwing-miniatures-SLK-Oct21FuseForceDoubleGasClouds.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/3752105/xwing-miniatures-SLK-Oct21FuseForceDoubleGasClouds.ttf.zip)

I think I'm done for October.   :)
