### ISSUE TITLE
Cleaner maneuver arrows, add Tallon Roll

### ISSUE THREAD

**Issue by armoredgear7** [geordanr/xwing-miniatures-font#8]
![screen shot 2015-11-23 at 3 19 00 pm](https://cloud.githubusercontent.com/assets/9486041/11348623/96b79986-91f5-11e5-8953-8cc9937a568a.png)

The new FFG Rules Reference PDF has the full set of maneuver arrows, and they have more consistent stroke weight/proportions than what's currently in this font. They're also shown all in context on a common baseline/x-height on page 6, so I was able to scale them as shown above.

I can edit the font to include these.

**Comment by Hinny** [comment]
I have thought about doing it as well but haven't found the energy to do it yet. So please go ahead and do that. Those documents are very good to extract symbols from.

**Comment by guidokessels** [comment]
Yeah they look great.

Would it be possible to add the icons for the epic ships also?

**Comment by armoredgear7** [comment]
Oh, um, yeah. I didn't realize they were missing :)

**Comment by guidokessels** [comment]
Thanks @armoredgear7 :)

**Comment by guidokessels** [comment]
Thanks for the huge ship icons @armoredgear7!

**Comment by timrisi** [comment]
Any word on Tallon Roll icons?

**Comment by guidokessels** [comment]
There in there:
```
xwing-miniatures-font-trollleft	
xwing-miniatures-font-trollright
```

**Comment by timrisi** [comment]
Huh.  I don't see them in the xwing-miniatures.ttf file (I'm actually looking at possibly using them in an iOS/android app, so can't use all the css etc to do it, would just be using the ttfs directly)

**Comment by geordanr** [comment]
I see them in the TTF; could it be a font caching issue?  Codepoints are `U+003A` and `U+003B` (colon and semicolon).

I'm going to close this issue (I should have closed it before when the font was actually updated); if it continues to be a problem reopen this issue.
