### ISSUE TITLE
Force Power icon very distorted

### ISSUE THREAD

**Issue by emeraldbeacon** [geordanr/xwing-miniatures-font#81]
Looking at the icon for Force Powers (uppercase F in the symbols font), it's extremely distorted at large sizes.  The action counterpart (lowercase H) is fairly clean, though... perhaps the upgrade icon could be... upgraded?  :D

**Comment by emeraldbeacon** [comment]
![image](https://user-images.githubusercontent.com/38739187/60299510-bc8e0b80-98e1-11e9-83e3-df3afcb38c1f.png)

**Comment by ScottKarch** [comment]
I made the first one, I'd assumed someone just copy pasted the icon into a circle.   I'll get it updated shortly.

**Comment by emeraldbeacon** [comment]
I'd love to join in with helping to make glyphs... I do know my way around basic Adobe Illustrator.  How exactly would I go about offering to assist?

**Comment by ScottKarch** [comment]
@emeraldbeacon I use the open source tool Font Forge to import/edit glyphs.  I trace bitmaps with the vector app named GRAPHIC on OSX, but it's just a cheap illustrator.  I export out vectors in SVG format then import them into Font Forge and resize.   Font forge has some rudimentary tools, but really only for tweaking.. I do all my work outside the font app and translate back and forth with SVG files.  Font Forge is open source and seems to work fine. 
https://fontforge.github.io/en-US/downloads/


GRAPHIC
![image](https://user-images.githubusercontent.com/19825797/67170566-62c1bd80-f378-11e9-8da0-8e77d84bc3f5.png)
FONT FORGE
![image](https://user-images.githubusercontent.com/19825797/67170578-7a00ab00-f378-11e9-940c-2bcfdf4c5a57.png)
after editing glyphs I just save and upload
![image](https://user-images.githubusercontent.com/19825797/67170638-d5cb3400-f378-11e9-9c93-723e34d0fac1.png)

I'm uploading the fixed force icon/token with the upload tonight...
