### ISSUE TITLE
Hyena and Naboo first pass

### ISSUE THREAD

**Issue by ScottKarch** [geordanr/xwing-miniatures-font#82]
Here is a first pass at them.
[x-wing-ships-sk-BETA.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/3331859/x-wing-ships-sk-BETA.ttf.zip)
![image](https://user-images.githubusercontent.com/19825797/60214048-5befc780-982a-11e9-8dc7-0aece94229fb.png)

**Comment by ScottKarch** [comment]
the hyena is just crazy looking up close.  
![image](https://user-images.githubusercontent.com/19825797/60214087-6dd16a80-982a-11e9-8e57-4fa303a0778d.png)

**Comment by ScottKarch** [comment]
[x-wing-ships-sk-BETA2.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/3331877/x-wing-ships-sk-BETA2.ttf.zip)
Hyena was upside down..  this font beta2 should be correct.

**Comment by emeraldbeacon** [comment]
Are either of these useable for you folks?  How (if at all) would you like them to be submitted for approval/updating?  
![image](https://user-images.githubusercontent.com/38739187/60759358-e24d9b80-9fd8-11e9-854f-589364ce195a.png)

**Comment by sirjorj** [comment]
Are high-res scans needed for anything else?  I could provide them.

**Comment by ScottKarch** [comment]
Are the hyena Naboo and transport/pod fine?  Do you want anything tweaked or should this Be closed?  Or are there tokens etc missing from the wave

**Comment by geordanr** [comment]
I think I just forgot to close this one out.
