### ISSUE TITLE
High-Res scans of Wave 4 things

### ISSUE THREAD

**Issue by sirjorj** [geordanr/xwing-miniatures-font#84]
![fuse](https://user-images.githubusercontent.com/6219508/62081340-fec7a700-b217-11e9-899e-9d4d0a6f6da9.jpg)
![hyena](https://user-images.githubusercontent.com/6219508/62081341-fec7a700-b217-11e9-935e-c6cb14d4a602.jpg)
![n1](https://user-images.githubusercontent.com/6219508/62081342-ff603d80-b217-11e9-96fe-446149e4f1a3.jpg)
![rtp](https://user-images.githubusercontent.com/6219508/62081343-ff603d80-b217-11e9-8b39-e1d31ddc873c.jpg)

**Comment by ScottKarch** [comment]
![image](https://user-images.githubusercontent.com/19825797/67151619-2fa2ff80-f28e-11e9-8221-812d648d8949.png)

**Comment by ScottKarch** [comment]
Are we standardizing on special icons just in circles?  Man.. this one is a total pain.  I'd like people to open it, print it and see if this works.  there is an overlap I don't like but I can't find a way to elimiate it yet.

**Comment by ScottKarch** [comment]
![image](https://user-images.githubusercontent.com/19825797/67151786-637f2480-f290-11e9-986a-12980c2d8777.png)

**Comment by ScottKarch** [comment]
[xwing-miniatures-SLK-OctFuse.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/3747212/xwing-miniatures-SLK-OctFuse.ttf.zip)

**Comment by ScottKarch** [comment]
In case anyone is curious...   it was made by lots of circles and rectangles and lots of different subtractions  
![image](https://user-images.githubusercontent.com/19825797/67151819-e7d1a780-f290-11e9-95e8-fb4934c91d11.png)
