### ISSUE TITLE
Wave V Icons

### ISSUE THREAD

**Issue by sirjorj** [geordanr/xwing-miniatures-font#88]
![btlb](https://user-images.githubusercontent.com/6219508/64901895-2659be00-d664-11e9-9d94-e19afee4a2d5.jpg)
![nantex](https://user-images.githubusercontent.com/6219508/64901896-28bc1800-d664-11e9-8de2-564af4cfad5a.jpg)

**Comment by ScottKarch** [comment]
I'll get started soon on these....

**Comment by sirjorj** [comment]
Thanks!

**Comment by ScottKarch** [comment]
![image](https://user-images.githubusercontent.com/19825797/67137847-0be5a800-f201-11e9-869e-fb8f00dd6889.png)

**Comment by ScottKarch** [comment]
[x-wing-ships-SLK-OctWave5.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/3746214/x-wing-ships-SLK-OctWave5.ttf.zip)
Nantex is semi-colon ; and BTL-B is the colon :

**Comment by ScottKarch** [comment]
I'm not sure how quickly they can be done, but I am guessing Gold Squadron uses this font for the stream ship icons.. it bugged me onstream that these were missing.  LOL

**Comment by dbxau** [comment]
Have updated stream.tabletop.to - so GSP should have them on stream now. Thanks!

**Comment by sirjorj** [comment]
Thank you much!

**Comment by ScottKarch** [comment]
You bet.  Thanks for getting that pushed out so quickly.   Looks good onstream.  If you want any additional glyphs for the app let me know.

**Comment by ScottKarch** [comment]
Dbxau, would you be able to have the overlay app place maneuver template shapes or stress/focus/tractor icons during their commentary? I can make glyphs to help with that.   Email me if I can help in any way. Scott@karchfamily.com

**Comment by geordanr** [comment]
CSS updated in ba60fe035b2857d4cc8e01bb0ba68d009ff7c21f
