### ISSUE TITLE
Wave 8 

### ISSUE THREAD

**Issue by SamDepasse** [geordanr/xwing-miniatures-font#9]
Do you plan an update with Wave 8 ships and other symbols (if any)?

**Comment by geordanr** [comment]
@armoredgear7 @Hinny

**Comment by armoredgear7** [comment]
I can do this; give me a couple days to find time to make it happen.

On Sunday, March 27, 2016, Geordan Rosario <notifications@github.com> wrote:

> @armoredgear7 <https://github.com/armoredgear7> @Hinny
> <https://github.com/Hinny>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/geordanr/xwing-miniatures-font/issues/9#issuecomment-202165728>
>


-- 
Josh Derksen

**Comment by SamDepasse** [comment]
If you guys need a bit of help, I could give a hand, provided you can indicate to me which tool/method shall be used.

**Comment by geordanr** [comment]
I think this issue is resolved and I just forgot to close it.
