### ISSUE TITLE
Command upgrade icon

### ISSUE THREAD

**Issue by PenalLegionnaire** [geordanr/xwing-miniatures-font#98]
Could someone please add the icon for the Command upgrade to the font? I have uploaded a photo of the icon on the physical card. I'm not sure how to help with the next step. Thanks!
![Command icon](https://user-images.githubusercontent.com/57696451/68731808-e8f7ab00-0596-11ea-93f4-5c3e007e64c5.jpg)

**Comment by ScottKarch** [comment]
I’ll do it this weekend. Anything else?

**Comment by PenalLegionnaire** [comment]
Thank you! This icon is the only one missing that I know of.

**Comment by J1mBob** [comment]
There is also the targeting-scope like glyph on the huge ship cards where the ships have the two initiative numbers.

**Comment by PenalLegionnaire** [comment]
Here's a picture of the icon that J1mBob mentioned. I'm sorry I don't have a better quality copy.  
![swz55_alderaanian-guard_card](https://user-images.githubusercontent.com/57696451/69109255-cead4980-0a3c-11ea-8d3d-e9982fc9b2ab.png)

**Comment by ScottKarch** [comment]
![image](https://user-images.githubusercontent.com/19825797/71334279-12dfae00-2503-11ea-8b5c-7e83ec3981fc.png)
and here is the little target one..   
![image](https://user-images.githubusercontent.com/19825797/71334767-20963300-2505-11ea-962b-6260dc7ace62.png)

**Comment by ScottKarch** [comment]
[xwing-miniatures SLK Dec22.ttf.zip](https://github.com/geordanr/xwing-miniatures-font/files/3993575/xwing-miniatures.SLK.Dec22.ttf.zip)
Attached is the font with all the glyphs from the open issues.  I'd appreciate any feedback.. especially which score/points version looks better.

**Comment by PenalLegionnaire** [comment]
Wonderful! Thanks for putting in the time on this. 

Regarding the victory points icons, I prefer the actual shape to the simplified version, but I haven't tried look at it in a smaller font yet.

**Comment by ScottKarch** [comment]
I find it's definitely worth looking at small versions either printed or on screen.   Download and try and use the glyphs in a realistic setting.  I think we should probably just stay with one design and I am fine with either.  I was thinking app/website designers could test it out in their products and see what works better and report back.  Some icons have already been simplified slightly so I thought I'd offer up 2 variants.

**Comment by ScottKarch** [comment]
Here are all the shapes added to the font above.
![image](https://user-images.githubusercontent.com/19825797/71369337-0ba2b980-2570-11ea-9590-56f834eabf38.png)
![image](https://user-images.githubusercontent.com/19825797/71369343-12313100-2570-11ea-83fc-097c9f384dff.png)
![image](https://user-images.githubusercontent.com/19825797/71369353-1eb58980-2570-11ea-92b3-94643200612b.png)
![image](https://user-images.githubusercontent.com/19825797/71369361-22491080-2570-11ea-9ec9-fbfa9d57a9c9.png)

**Comment by PenalLegionnaire** [comment]
I like having the two options for the victory point icon because the simplified version looks better in small font but the original version looks really nice when it's large, but I understand that having two of the same icon would break with precedent. I linked to https://www.reddit.com/r/XWingTMG/comments/eeuxn4/new_icons_at_geordanrxwingminiaturesfont/ and asked which version people prefer.

**Comment by sirjorj** [comment]
I posted an image on the victory counter issue (https://github.com/geordanr/xwing-miniatures-font/issues/100) of an environment card that uses the icon.  It looks like it uses the more complex version but it doesn't have the circle around it.

**Comment by ScottKarch** [comment]
Thanks for asking on reddit. If you guys know the various app developers or squad builder websites I’m open to make just about it anything that requested.       I do like the option for both high res and low res icon versions.  ( similar to the strain... I think the solid shape will look better in small fonts and the one with knockouts )
Report back the voting or what
Is the thought here?

**Comment by PenalLegionnaire** [comment]
As you probably saw, people on Reddit upvoted but didn't comment. I should have provided some method for anonymous voting. 
I believe u/raithosu does YASB, u/FixingKitty does Launch Bay Next, and u/antigrapist does Meta-Wing and List Fortress. I don't know them personally.

**Comment by biffindy** [comment]
I have a suggestion for additional glyphs - the symbols associated with the Wing Leader (triangles) and Wingmates (circles).  I've added a screen shot from the Epic Battles news article which shows a wing card.   Resolution is not the best, but hope it identifies the symbols requested.
![image](https://user-images.githubusercontent.com/52855391/71642217-f287c000-2c75-11ea-8378-104590ffc1a3.png)

**Comment by ScottKarch** [comment]
This was added to the last release. I think it can be closed.
