### ISSUE TITLE
Strain and deplete icons

### ISSUE THREAD

**Issue by urbknu** [geordanr/xwing-miniatures-font#99]
Hi, guys

Love your work, and much of the community would not have the same finish on their projects without you. 

Just wondering, are strain and deplete icons in the works?

**Comment by ScottKarch** [comment]
Deplete looks like the old attack value icon from 1st edition.
Right now it's %
![image](https://user-images.githubusercontent.com/19825797/71329251-8de79b00-24e8-11ea-8c55-894460a65a7c.png)
Here is the square depleted "D" and a square strain "N"
![image](https://user-images.githubusercontent.com/19825797/71332722-dc069980-24fc-11ea-9e3f-35d13dcaef33.png)

There is already a strain but not in square token shape.   What's the vote on these two?

**Comment by npiegdon** [comment]
The strain icon should have a little cutout in each of the three arrow segments.  If I could, I'd like to contribute the icon I made using a high-resolution scan from one of the new strain tokens.  The vector version can be found in the "X-Wing Quick Refererence.ai" Illustrator file, [here](https://github.com/npiegdon/xwing2-quick-reference).

That version has a nice, minimal vertex count and matches the size/shape of the updated icon just about exactly.

![deplete](https://user-images.githubusercontent.com/2000287/71416539-d7da9900-262e-11ea-8361-cc93cef563c8.png)

Please let me know if that's enough to work with.  I'm less familiar with font editors, but I could try to get it into the correct format, if it still needs more work.

**Comment by ScottKarch** [comment]
Thanks. I almost did it as well.    An illustrator eps or svg file is how I moved things in and out.   I use FontForge for creating the fonts. Any vector app that can output svg will work to create the glyphs.  


I’ll try and update the strain.

**Comment by ScottKarch** [comment]
OK  I'd like guidance on a couple things.
1) Should we replace the solid strain with the more accurate strain? Leave both? Solid for small font sizes and accurate for larger?
2) I reworked the square shape..  In the previous shape, the horizonal lines don't look the same width as the angled lines..   I think this shape looks better.... I also like the slightly narrower ends.
3) votes on leaving simplified and accurate point tokens.
![image](https://user-images.githubusercontent.com/19825797/71534625-b21af180-28c5-11ea-8870-e05e244cc98c.png)
![image](https://user-images.githubusercontent.com/19825797/71534666-e2fb2680-28c5-11ea-8755-2111dfd717a3.png)

**Comment by ScottKarch** [comment]
This was added to the last release. I think it can be closed.
